<script lang="ts">
  import { api } from '$lib/api';
  const featureDisabled = true;
  const serviceTypes = ['fiber', 'dsl', 'cable', 'wireless', 'leased_line', 'satellite', 'other'] as const;
  const statuses = ['planned', 'active', 'degraded', 'suspended', 'terminated'] as const;
  const addressingModes = ['static', 'dhcp', 'dynamic', 'pppoe', 'cgnat', 'unknown'] as const;
  let branchId = $state(''); let providerName = $state(''); let circuitLabel = $state(''); let serviceType = $state('fiber'); let status = $state('planned'); let demarcLocation = $state(''); let downloadMbps = $state(''); let uploadMbps = $state(''); let addressingMode = $state('unknown'); let providerCircuitIdMasked = $state(''); let saving = $state(false); let error = $state(''); let saved = $state(false);
  async function submit() { error = ''; saved = false; const download = Number(downloadMbps); const upload = Number(uploadMbps); if (!branchId.trim() || !providerName.trim() || !circuitLabel.trim() || !(download > 0) || !(upload > 0)) { error = 'Branch ID, provider, circuit label, and positive speeds are required.'; return; } saving = true; try { await api.post('/api/isp-circuits', { branchId: branchId.trim(), providerName: providerName.trim(), circuitLabel: circuitLabel.trim(), serviceType, status, demarcLocation: demarcLocation.trim() || undefined, downloadMbps: download, uploadMbps: upload, addressingMode, providerCircuitIdMasked: providerCircuitIdMasked.trim() || undefined }, { 'Idempotency-Key': crypto.randomUUID() }); saved = true; } catch (caught) { error = caught instanceof Error ? caught.message : 'Unable to save ISP circuit.'; } finally { saving = false; } }
</script>
<svelte:head><title>ISP circuit intake — Oracle Inventory</title></svelte:head>
<div class="page"><a href="/infrastructure/servers" class="back">← Servers and connectivity</a><header><p class="eyebrow">Manual intake</p><h1>ISP circuit</h1><p>Record provider and service metadata only. Do not enter credentials, PPPoE secrets, account passwords, or private keys.</p></header><section class="notice" role="status"><strong>Temporarily disabled</strong><p>Phase 5 remains fail-closed until the migration, permission review, and rollout are approved.</p></section><form class="card" onsubmit={(event) => { event.preventDefault(); submit(); }}><fieldset disabled={featureDisabled || saving}><legend>Circuit metadata</legend><label for="branch">Branch ID <span aria-hidden="true">*</span><input id="branch" bind:value={branchId} autocomplete="off" /></label><div class="two-up"><label for="provider">Provider <span aria-hidden="true">*</span><input id="provider" bind:value={providerName} maxlength="160" /></label><label for="label">Circuit label <span aria-hidden="true">*</span><input id="label" bind:value={circuitLabel} maxlength="160" /></label></div><div class="two-up"><label for="service">Service type<select id="service" bind:value={serviceType}>{#each serviceTypes as item}<option value={item}>{item}</option>{/each}</select></label><label for="status">Status<select id="status" bind:value={status}>{#each statuses as item}<option value={item}>{item}</option>{/each}</select></label></div><div class="two-up"><label for="down">Download Mbps <span aria-hidden="true">*</span><input id="down" type="number" min="1" bind:value={downloadMbps} /></label><label for="up">Upload Mbps <span aria-hidden="true">*</span><input id="up" type="number" min="1" bind:value={uploadMbps} /></label></div><label for="addressing">Addressing mode<select id="addressing" bind:value={addressingMode}>{#each addressingModes as item}<option value={item}>{item}</option>{/each}</select></label><label for="demarc">Demarc location<input id="demarc" bind:value={demarcLocation} maxlength="240" /></label><label for="masked-id">Masked provider circuit ID <span class="optional">(never a credential)</span><input id="masked-id" bind:value={providerCircuitIdMasked} maxlength="120" /></label><button type="submit">{saving ? 'Saving…' : 'Save ISP circuit'}</button></fieldset>{#if error}<p class="error" role="alert">{error}</p>{/if}{#if saved}<p class="success" role="status">ISP circuit saved.</p>{/if}</form></div>
<style>.page{max-width:760px;margin:0 auto;padding:32px 24px 48px}.back{color:var(--body);text-decoration:none}.eyebrow{margin:24px 0 5px;color:var(--mute);font-size:12px;font-weight:700;letter-spacing:.08em;text-transform:uppercase}h1{margin:0;color:var(--ink);font-size:32px}header p:last-child{color:var(--body)}.card,.notice{border:1px solid var(--hairline);border-radius:12px;background:var(--canvas);padding:24px;margin-top:18px}.notice{border-color:#d6a400;background:color-mix(in srgb,#d6a400 8%,var(--canvas))}.notice p{margin-bottom:0}.card fieldset{border:0;padding:0;margin:0}.card legend{font-size:18px;font-weight:700}label{display:block;margin:18px 0 6px;font-weight:650}input,select{box-sizing:border-box;width:100%;border:1px solid var(--hairline);border-radius:8px;padding:10px 12px;background:var(--canvas);color:var(--ink);font:inherit}.two-up{display:grid;grid-template-columns:1fr 1fr;gap:16px}.optional{color:var(--mute);font-weight:400}button{margin-top:22px;border:0;border-radius:8px;padding:10px 14px;background:var(--ink);color:var(--on-primary);font:inherit;font-weight:650}fieldset:disabled input,fieldset:disabled select,button:disabled{opacity:.55;cursor:not-allowed}.error{color:var(--error)}.success{color:var(--success,#15803d)}@media(max-width:640px){.page{padding:24px 16px}.two-up{grid-template-columns:1fr}}
</style>
