<script lang="ts">
  import { onMount } from 'svelte';
  import { api } from '$lib/api';
  type Asset = { id: string; name: string; assetTag?: string | null; category?: { name?: string } };
  let assets: Asset[] = [], assetId = '', updatedAt = '', environment = 'production', criticality = 'medium', virtualizationRole = 'physical', serviceOwner = '';
  let review = false, status = '', error = '', loading = true;
  async function load() { loading = true; error = ''; try { const result = await api.get<{ items?: Asset[] } | Asset[]>('/api/assets'); assets = Array.isArray(result) ? result : result.items ?? []; assets = assets.filter((asset) => /server/i.test(asset.category?.name ?? '')); } catch (e) { error = (e as Error).message; } finally { loading = false; } }
  onMount(load);
  let previousAsset = '';
  $effect(() => { if (assetId && assetId !== previousAsset) { previousAsset = assetId; selectAsset(); } });
  async function selectAsset() { updatedAt = ''; if (!assetId) return; try { const profile = await api.get<{ updatedAt?: string; environment?: string; criticality?: string; virtualizationRole?: string; serviceOwner?: string } | null>(`/api/servers/${assetId}/profile`); if (profile) { updatedAt = profile.updatedAt ?? ''; environment = profile.environment ?? environment; criticality = profile.criticality ?? criticality; virtualizationRole = profile.virtualizationRole ?? virtualizationRole; serviceOwner = profile.serviceOwner ?? serviceOwner; } } catch (e) { error = (e as Error).message; } }
  const payload = () => ({ asset: assets.find((item) => item.id === assetId)?.name ?? assetId, environment, criticality, virtualizationRole, serviceOwner, updatedAt: updatedAt || 'new profile' });
  async function save() { error = ''; try { await api.put(`/api/servers/${assetId}/profile`, { environment, criticality, virtualizationRole, serviceOwner, ...(updatedAt ? { expectedUpdatedAt: updatedAt } : {}) }); status = 'Server profile saved.'; review = false; } catch (e) { if ((e as Error).message.includes('changed')) { await selectAsset(); review = true; error = 'The profile changed. Values were refreshed; review and confirm again.'; } else error = (e as Error).message; } }
</script>
<svelte:head><title>Server intake</title></svelte:head>
<div class="page"><h1>Server intake</h1><p>Metadata only. Credentials and configuration exports are never accepted.</p>
{#if loading}<section class="panel" role="status">Loading authorized server assets…</section>{:else if error && !review}<section class="panel" role="alert"><p class="error">{error}</p><button type="button" onclick={load}>Retry</button></section>{:else if review}<section class="panel" aria-labelledby="review-title"><h2 id="review-title">Review before saving</h2><dl>{#each Object.entries(payload()) as [key, value]}<div><dt>{key}</dt><dd>{value || '—'}</dd></div>{/each}</dl><p>Primary/role lifecycle changes are managed from the server detail view with expectedUpdatedAt protection.</p><button type="button" onclick={save} disabled={!assetId}>Confirm and save</button><button type="button" class="secondary" onclick={() => review = false}>Back to edit</button></section>{:else}<section class="panel">{#if assets.length === 0}<p>No authorized Server-category assets are available.</p>{:else}<label for="asset">Server asset</label><select id="asset" bind:value={assetId} aria-describedby="asset-help"><option value="">Select an authorized server</option>{#each assets as asset}<option value={asset.id}>{asset.name} · {asset.assetTag ?? 'No tag'}</option>{/each}</select><small id="asset-help">Branch and object scope are enforced by the API.</small><label for="environment">Environment</label><select id="environment" bind:value={environment}><option>production</option><option>staging</option><option>development</option><option>test</option><option>other</option></select><label for="criticality">Criticality</label><select id="criticality" bind:value={criticality}><option>critical</option><option>high</option><option>medium</option><option>low</option></select><label for="virtualization">Virtualization role</label><select id="virtualization" bind:value={virtualizationRole}><option>physical</option><option>hypervisor</option><option>virtual_machine</option><option>container_host</option><option>other</option></select><label for="owner">Service owner</label><input id="owner" bind:value={serviceOwner} /><button type="button" onclick={() => { error = ''; review = true; }} disabled={!assetId}>Review server profile</button>{/if}</section>{/if}
{#if error && review}<p role="alert" class="error">{error}</p>{/if}{#if status}<p role="status" class="ok">{status}</p>{/if}</div>
<style>.page{max-width:700px;margin:0 auto;padding:32px}.panel{border:1px solid #ddd;border-radius:10px;padding:20px}label{display:block;margin:12px 0 5px;font-weight:600}input,select{display:block;width:100%;padding:8px}small{display:block}.error{color:#b91c1c}.ok{color:#166534}button{margin-top:18px;padding:10px 14px}.secondary{margin-left:8px}</style>
