<script lang="ts">
  import { api } from '$lib/api';
  const featureDisabled = true;
  const environments = ['production', 'staging', 'development', 'test', 'other'] as const;
  const criticalities = ['critical', 'high', 'medium', 'low'] as const;
  const virtualizationRoles = ['physical', 'hypervisor', 'virtual_machine', 'container_host', 'other'] as const;
  let assetId = $state(''); let environment = $state('production'); let criticality = $state('medium'); let virtualizationRole = $state('physical'); let serviceOwner = $state(''); let supportOwner = $state(''); let purpose = $state(''); let saving = $state(false); let error = $state(''); let saved = $state(false);
  async function submit() { error = ''; saved = false; if (!assetId.trim() || !serviceOwner.trim()) { error = 'An existing server Asset ID and service owner are required.'; return; } saving = true; try { const response = await api.raw(`/api/servers/${encodeURIComponent(assetId.trim())}/profile`, { method: 'PUT', headers: { 'Content-Type': 'application/json', 'Idempotency-Key': crypto.randomUUID() }, body: JSON.stringify({ environment, criticality, virtualizationRole, serviceOwner: serviceOwner.trim(), supportOwner: supportOwner.trim() || undefined, purpose: purpose.trim() || undefined }) }); if (!response.ok) { const body = await response.json().catch(() => ({})) as { error?: string }; throw new Error(body.error ?? `HTTP ${response.status}`); } saved = true; } catch (caught) { error = caught instanceof Error ? caught.message : 'Unable to save server profile.'; } finally { saving = false; } }
</script>
<svelte:head><title>Server intake — Oracle Inventory</title></svelte:head>
<div class="page"><a href="/infrastructure/servers" class="back">← Servers and connectivity</a><header><p class="eyebrow">Manual intake</p><h1>Server profile</h1><p>Record metadata against an existing Asset. Do not enter passwords, tokens, firewall rules, raw configuration, or backup keys.</p></header>
  <section class="notice" role="status"><strong>Temporarily disabled</strong><p>Phase 5 is coded fail-closed. The form is preserved for review and will remain unavailable until the feature flag, migration, and rollout are approved.</p></section>
  <form class="card" onsubmit={(event) => { event.preventDefault(); submit(); }}><fieldset disabled={featureDisabled || saving}><legend>Server metadata</legend><label for="asset-id">Existing server Asset ID <span aria-hidden="true">*</span></label><input id="asset-id" bind:value={assetId} autocomplete="off" placeholder="Asset ID" /><div class="two-up"><label for="environment">Environment<select id="environment" bind:value={environment}>{#each environments as item}<option value={item}>{item}</option>{/each}</select></label><label for="criticality">Criticality<select id="criticality" bind:value={criticality}>{#each criticalities as item}<option value={item}>{item}</option>{/each}</select></label></div><label for="virtualization">Virtualization role<select id="virtualization" bind:value={virtualizationRole}>{#each virtualizationRoles as item}<option value={item}>{item}</option>{/each}</select></label><label for="owner">Service owner <span aria-hidden="true">*</span><input id="owner" bind:value={serviceOwner} maxlength="160" /></label><label for="support">Support owner <span class="optional">(optional)</span><input id="support" bind:value={supportOwner} maxlength="160" /></label><label for="purpose">Purpose <span class="optional">(metadata only)</span><textarea id="purpose" bind:value={purpose} maxlength="1000" rows="4"></textarea></label><button type="submit">{saving ? 'Saving…' : 'Save server profile'}</button></fieldset>{#if error}<p class="error" role="alert">{error}</p>{/if}{#if saved}<p class="success" role="status">Server profile saved.</p>{/if}</form>
</div>
<style>.page{max-width:760px;margin:0 auto;padding:32px 24px 48px}.back{color:var(--body);text-decoration:none}.eyebrow{margin:24px 0 5px;color:var(--mute);font-size:12px;font-weight:700;letter-spacing:.08em;text-transform:uppercase}h1{margin:0;color:var(--ink);font-size:32px}header p:last-child{color:var(--body)}.card,.notice{border:1px solid var(--hairline);border-radius:12px;background:var(--canvas);padding:24px;margin-top:18px}.notice{border-color:#d6a400;background:color-mix(in srgb,#d6a400 8%,var(--canvas))}.notice p{margin-bottom:0}.card fieldset{border:0;padding:0;margin:0}.card legend{font-size:18px;font-weight:700;margin-bottom:4px}label{display:block;margin:18px 0 6px;font-weight:650}input,select,textarea{box-sizing:border-box;width:100%;border:1px solid var(--hairline);border-radius:8px;padding:10px 12px;background:var(--canvas);color:var(--ink);font:inherit}textarea{resize:vertical}.two-up{display:grid;grid-template-columns:1fr 1fr;gap:16px}.optional{color:var(--mute);font-weight:400}button{margin-top:22px;border:0;border-radius:8px;padding:10px 14px;background:var(--ink);color:var(--on-primary);font:inherit;font-weight:650}button:disabled,fieldset:disabled input,fieldset:disabled select,fieldset:disabled textarea{opacity:.55;cursor:not-allowed}.error{color:var(--error)}.success{color:var(--success,#15803d)}@media(max-width:640px){.page{padding:24px 16px}.two-up{grid-template-columns:1fr}}
</style>
