<script lang="ts">
  import { goto } from '$app/navigation';
  import { onMount } from 'svelte';
  import { api } from '$lib/api';
  import { can } from '$lib/utils/permissions';
  import { authStore } from '$lib/stores/auth.svelte';
  type Component = { type: 'ram' | 'storage'; slotOrBay?: string; brand?: string; model?: string; serialNumber?: string; capacity?: string; storageKind?: string };
  type Form = { name: string; assetTag: string; computerName: string; serialNumber: string; brand: string; model: string; deviceType: 'computer'|'laptop'; categoryId: string; branchId: string; employeeId: string; ownership: string; condition: string; status: string; description: string; purchaseDate: string; warrantyExpiry: string; processor: string; motherboard: string; operatingSystem: string; osVersion: string; osInstallDate: string; components: Component[] };
  type Option = { id: string; name: string; employeeId?: string | null };
  const blank = (): Form => ({ name:'', assetTag:'', computerName:'', serialNumber:'', brand:'', model:'', deviceType:'computer', categoryId:'', branchId:'', employeeId:'', ownership:'company', condition:'usable', status:'active', description:'', purchaseDate:'', warrantyExpiry:'', processor:'', motherboard:'', operatingSystem:'', osVersion:'', osInstallDate:'', components:[] });
  let form = $state(blank()); let categories = $state<Option[]>([]); let branches = $state<Option[]>([]); let employees = $state<Option[]>([]); let draftId = $state(''); let draftVersion = $state(''); let error = $state(''); let notice = $state(''); let loading = $state(true); let saving = $state(false); let reviewing = $state(false); let forbidden = $state(false); let duplicateComputerName = $state(false); let tagUnavailable = $state(false);
  onMount(async () => { const role = authStore.user?.role?.trim().toLowerCase(); if (!can('create_inventory') || (role !== 'admin' && role !== 'super_admin')) { forbidden = true; loading = false; return; } try { const [lookup, drafts] = await Promise.all([api.get<{ categories: Option[]; branches: Option[]; employees: Option[] }>('/api/computer-intake/lookups'), api.get<{ id: string; updatedAt: string; data: Form }[]>('/api/computer-intake/drafts')]); categories = lookup.categories; branches = lookup.branches; employees = lookup.employees; const latest = drafts[0]; if (latest) { draftId = latest.id; draftVersion = latest.updatedAt; form = { ...blank(), ...latest.data, components: latest.data.components ?? [] }; notice = 'Latest draft loaded. Review before submitting.'; } } catch (e) { error = (e as Error).message; } finally { loading = false; } });
  function add(type: 'ram'|'storage') { form.components = [...form.components, { type }]; }
  function remove(index: number) { form.components = form.components.filter((_, i) => i !== index); }
  async function save() { saving = true; error=''; try { const body = draftId ? { ...form, expectedUpdatedAt: draftVersion } : form; const row = draftId ? await api.put<{ id:string; updatedAt:string }>(`/api/computer-intake/drafts/${draftId}`, body) : await api.post<{ id:string; updatedAt:string }>('/api/computer-intake/drafts', form); draftId = row.id; draftVersion = row.updatedAt; notice = 'Draft saved.'; } catch(e) { error=(e as Error).message; } finally { saving=false; } }
  async function review() { error=''; if (!form.name.trim() || !form.branchId) { error='Computer name and branch are required.'; return; } if (!draftId) { await save(); } if (draftId) { try { const check = await api.get<{ duplicateComputerName: boolean; assetTagAvailable: boolean; updatedAt: string }>(`/api/computer-intake/drafts/${draftId}/preflight`); duplicateComputerName = check.duplicateComputerName; tagUnavailable = !check.assetTagAvailable; draftVersion = check.updatedAt; } catch (e) { error = (e as Error).message; return; } } reviewing=true; }
  async function submit() { saving=true; error=''; try { if (!draftId) { const row = await api.post<{ id:string; updatedAt:string }>('/api/computer-intake/drafts', form); draftId=row.id; draftVersion=row.updatedAt; } await api.post(`/api/computer-intake/drafts/${draftId}/submit`, { expectedUpdatedAt: draftVersion }, { 'Idempotency-Key': `computer-intake-${draftId}-${draftVersion}` }); goto('/assets'); } catch(e) { error=(e as Error).message; } finally { saving=false; } }
</script>
<svelte:head><title>New Computer Intake</title></svelte:head>
<div class="page">
  {#if forbidden}<section class="card forbidden" role="alert"><h1>Computer intake unavailable</h1><p>You need Admin or Super Admin access with inventory creation permission.</p><button class="primary" onclick={() => goto('/assets')}>Return to assets</button></section>{:else}
  <nav aria-label="Breadcrumb"><a href="/assets">Assets</a><span aria-hidden="true"> / </span><strong>New computer</strong></nav>
  <header><div><h1>New computer intake</h1><p>Manual Mode · official inventory record</p></div><div class="actions"><button class="ghost" onclick={() => goto('/assets')}>Cancel</button><button onclick={save} disabled={saving || loading}>Save draft</button><button class="primary" onclick={review} disabled={saving || loading}>Review</button></div></header>
  {#if error}<div class="alert error" role="alert">{error}</div>{/if}{#if notice}<div class="alert success" role="status">{notice}</div>{/if}
  <div class="note">Manual values become official only after confirmation. Never enter passwords, product keys, or credentials.</div>
  {#if reviewing}<section class="card" aria-labelledby="review-title"><div class="section-head"><h2 id="review-title">Review and confirm</h2><button class="ghost" onclick={() => reviewing=false}>Back to edit</button></div>{#if duplicateComputerName}<div class="alert warning" role="alert">Warning: this computer name already exists in the branch. Confirm this is a separate device.</div>{/if}{#if tagUnavailable}<div class="alert error" role="alert">This asset tag is already in use. Change it before submitting.</div>{/if}<dl><dt>Name</dt><dd>{form.name}</dd><dt>Asset tag</dt><dd>{form.assetTag || 'Not provided'}</dd><dt>Branch</dt><dd>{branches.find(x => x.id === form.branchId)?.name || 'Missing'}</dd><dt>Assignment</dt><dd>{employees.find(x => x.id === form.employeeId)?.name || 'Unassigned'}</dd><dt>Specifications</dt><dd>{[form.brand, form.model, form.processor, form.operatingSystem].filter(Boolean).join(' · ') || 'Not provided'}</dd></dl><button class="primary" onclick={submit} disabled={saving || tagUnavailable}>Confirm and submit official record</button></section>{/if}
  <form onsubmit={(e) => { e.preventDefault(); review(); }}>
    <section class="card"><h2>1. Identity</h2><div class="grid"><label>Computer name *<input bind:value={form.name} required placeholder="Finance-LT-014" /></label><label>Asset tag<input bind:value={form.assetTag} /></label><label>Serial number<input bind:value={form.serialNumber} /></label><label>Network computer name<input bind:value={form.computerName} /></label><label>Brand<input bind:value={form.brand} /></label><label>Model<input bind:value={form.model} /></label><label>Category<select bind:value={form.categoryId}><option value="">Select category</option>{#each categories as item}<option value={item.id}>{item.name}</option>{/each}</select></label><label>Device type<select bind:value={form.deviceType}><option value="computer">Desktop</option><option value="laptop">Laptop</option></select></label></div></section>
    <section class="card"><h2>2. Branch and lifecycle</h2><div class="grid"><label>Branch / location *<select bind:value={form.branchId} required><option value="">Select active branch</option>{#each branches as item}<option value={item.id}>{item.name}</option>{/each}</select></label><p class="field-note">Ownership: <strong>Company</strong> (Phase 1 supports company inventory only).</p><label>Condition<select bind:value={form.condition}><option value="usable">Usable</option><option value="for_repair">For repair</option><option value="for_disposal">For disposal</option></select></label><label>Status<select bind:value={form.status}><option value="active">Active</option><option value="lost">Lost</option><option value="stolen">Stolen</option></select></label><label>Purchase date<input type="date" bind:value={form.purchaseDate} /></label><label>Warranty expiry<input type="date" bind:value={form.warrantyExpiry} /></label></div></section>
    <section class="card"><h2>3. Specifications</h2><div class="grid"><label>Processor<input bind:value={form.processor} /></label><label>Motherboard<input bind:value={form.motherboard} /></label><label>Operating system<input bind:value={form.operatingSystem} /></label><label>OS version<input bind:value={form.osVersion} /></label><label>OS install date<input type="date" bind:value={form.osInstallDate} /></label></div><div class="components"><div class="section-head"><h3>RAM and storage</h3><div><button type="button" class="link" onclick={() => add('ram')}>+ RAM row</button><button type="button" class="link" onclick={() => add('storage')}>+ Storage row</button></div></div>{#if form.components.length === 0}<p class="muted">Optional repeatable component rows.</p>{/if}{#each form.components as component, index}<div class="component"><strong>{component.type === 'ram' ? 'RAM' : 'Storage'}</strong><input aria-label="Slot or bay" bind:value={component.slotOrBay} placeholder="Slot / bay" /><input aria-label="Brand" bind:value={component.brand} placeholder="Brand" /><input aria-label="Model" bind:value={component.model} placeholder="Model" /><input aria-label="Serial number" bind:value={component.serialNumber} placeholder="Serial" /><input aria-label="Capacity" bind:value={component.capacity} placeholder="Capacity" /><button type="button" class="remove" onclick={() => remove(index)}>Remove</button></div>{/each}</div></section>
    <section class="card"><h2>4. Optional assignment</h2><div class="grid"><label>Custodian / employee<select bind:value={form.employeeId}><option value="">Leave unassigned</option>{#each employees as item}<option value={item.id}>{item.name}{item.employeeId ? ` · ${item.employeeId}` : ''}</option>{/each}</select></label><label>Notes<textarea bind:value={form.description}></textarea></label></div></section>
    <div class="bottom"><button type="button" class="ghost" onclick={save}>Save draft</button><button type="submit" class="primary" disabled={saving}>Review and submit</button></div>
  </form>
  {/if}
</div>
<style>
  .page{max-width:1100px;margin:0 auto;padding:28px 32px 60px;color:var(--ink)}nav{color:var(--mute);font-size:13px;margin-bottom:24px}nav a{color:var(--link)}header,.section-head,.actions,.bottom{display:flex;justify-content:space-between;align-items:flex-start;gap:12px}h1{margin:0;font-size:26px}header p{color:var(--mute);margin:6px 0 22px}.actions,.bottom{flex-wrap:wrap}.card{background:var(--canvas);border:1px solid var(--hairline);border-radius:10px;padding:22px;margin:14px 0}.card h2{font-size:16px;margin:0 0 18px}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px 22px}label{display:flex;flex-direction:column;gap:6px;font-size:12px;font-weight:600}input,select,textarea,button{font:inherit}input,select,textarea{color:var(--ink);background:var(--canvas);border:1px solid var(--hairline);border-radius:7px;padding:9px;min-height:36px}textarea{min-height:80px}button{border:1px solid var(--hairline);background:var(--canvas);border-radius:7px;padding:8px 13px;cursor:pointer}button:focus-visible,input:focus-visible,select:focus-visible,textarea:focus-visible{outline:2px solid var(--link);outline-offset:2px}.primary{background:var(--ink);color:var(--on-primary);border-color:var(--ink)}.ghost{background:transparent}.alert,.note{padding:12px 14px;border-radius:8px;margin:12px 0;font-size:13px}.alert.error{background:var(--error-soft);color:var(--error)}.alert.success{background:oklch(94% .04 150);color:oklch(35% .12 150)}.note{background:var(--canvas-soft-2)}.components{border-top:1px solid var(--hairline);padding-top:18px;margin-top:18px}.link{border:0;background:none;color:var(--link);padding:4px}.muted{color:var(--mute);font-size:12px}.component{display:grid;grid-template-columns:70px repeat(5,minmax(0,1fr)) 55px;gap:7px;align-items:center;margin-top:10px}.component input{min-width:0;padding:7px}.remove{border:0;background:none;color:var(--error);padding:4px}.bottom{justify-content:flex-end;margin-top:20px}dl{display:grid;grid-template-columns:140px 1fr;gap:10px;margin:18px 0}dt{color:var(--mute)}dd{margin:0}@media(max-width:760px){.page{padding:20px 16px}.grid{grid-template-columns:1fr}header{display:block}.component{grid-template-columns:1fr 1fr}.component strong{grid-column:span 2}}
</style>
