-- Phase 6 additive stock foundation. Feature remains server-disabled until rollout approval.
CREATE TYPE "StockLocationType" AS ENUM ('room','cabinet','vehicle','employee_custody','other');
CREATE TYPE "StockMovementType" AS ENUM ('receive','issue','transfer','adjustment','count_correction','consume','return','opening');
CREATE TYPE "StockCountStatus" AS ENUM ('draft','submitted','approved','rejected','cancelled');
CREATE TABLE "StockItem" ("id" TEXT PRIMARY KEY,"sku" TEXT NOT NULL UNIQUE,"name" TEXT NOT NULL,"category" TEXT NOT NULL,"unitOfMeasure" TEXT NOT NULL,"description" TEXT,"isSerialized" BOOLEAN NOT NULL DEFAULT false,"active" BOOLEAN NOT NULL DEFAULT true,"archivedAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "StockLocation" ("id" TEXT PRIMARY KEY,"branchId" TEXT NOT NULL,"name" TEXT NOT NULL,"locationType" "StockLocationType" NOT NULL,"description" TEXT,"archivedAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "StockMovement" ("id" TEXT PRIMARY KEY,"stockItemId" TEXT NOT NULL,"movementType" "StockMovementType" NOT NULL,"quantity" DECIMAL(18,3) NOT NULL,"reason" TEXT,"referenceType" TEXT,"referenceId" TEXT,"idempotencyKey" TEXT NOT NULL UNIQUE,"performedById" TEXT NOT NULL,"approvedById" TEXT,"approvedAt" TIMESTAMP(3),"relatedEmployeeId" TEXT,"relatedAssetId" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "StockLedgerEntry" ("id" TEXT PRIMARY KEY,"movementId" TEXT NOT NULL,"locationId" TEXT NOT NULL,"quantityDelta" DECIMAL(18,3) NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE "StockLevelPolicy" ("id" TEXT PRIMARY KEY,"stockItemId" TEXT NOT NULL,"locationId" TEXT NOT NULL,"minimumQuantity" DECIMAL(18,3) NOT NULL,"reorderQuantity" DECIMAL(18,3) NOT NULL,"updatedAt" TIMESTAMP(3) NOT NULL);
CREATE TABLE "StockCountSession" ("id" TEXT PRIMARY KEY,"locationId" TEXT NOT NULL,"status" "StockCountStatus" NOT NULL DEFAULT 'draft',"startedById" TEXT NOT NULL,"submittedAt" TIMESTAMP(3),"approvedById" TEXT,"approvedAt" TIMESTAMP(3),"expectedUpdatedAt" TIMESTAMP(3) NOT NULL,"idempotencyKey" TEXT NOT NULL UNIQUE,"approvalIdempotencyKey" TEXT UNIQUE);
CREATE TABLE "StockCountLine" ("id" TEXT PRIMARY KEY,"sessionId" TEXT NOT NULL,"stockItemId" TEXT NOT NULL,"expectedQuantitySnapshot" DECIMAL(18,3) NOT NULL,"countedQuantity" DECIMAL(18,3) NOT NULL,"variance" DECIMAL(18,3) NOT NULL);
CREATE UNIQUE INDEX "StockLevelPolicy_item_location_key" ON "StockLevelPolicy"("stockItemId","locationId"); CREATE UNIQUE INDEX "StockCountLine_session_item_key" ON "StockCountLine"("sessionId","stockItemId");
ALTER TABLE "StockMovement" ADD CONSTRAINT "StockMovement_item_fk" FOREIGN KEY ("stockItemId") REFERENCES "StockItem"("id") ON DELETE RESTRICT; ALTER TABLE "StockLedgerEntry" ADD CONSTRAINT "StockLedgerEntry_movement_fk" FOREIGN KEY ("movementId") REFERENCES "StockMovement"("id") ON DELETE RESTRICT; ALTER TABLE "StockLedgerEntry" ADD CONSTRAINT "StockLedgerEntry_location_fk" FOREIGN KEY ("locationId") REFERENCES "StockLocation"("id") ON DELETE RESTRICT; ALTER TABLE "StockLevelPolicy" ADD CONSTRAINT "StockLevelPolicy_item_fk" FOREIGN KEY ("stockItemId") REFERENCES "StockItem"("id") ON DELETE CASCADE; ALTER TABLE "StockLevelPolicy" ADD CONSTRAINT "StockLevelPolicy_location_fk" FOREIGN KEY ("locationId") REFERENCES "StockLocation"("id") ON DELETE CASCADE; ALTER TABLE "StockCountSession" ADD CONSTRAINT "StockCountSession_location_fk" FOREIGN KEY ("locationId") REFERENCES "StockLocation"("id") ON DELETE RESTRICT; ALTER TABLE "StockCountLine" ADD CONSTRAINT "StockCountLine_session_fk" FOREIGN KEY ("sessionId") REFERENCES "StockCountSession"("id") ON DELETE CASCADE; ALTER TABLE "StockCountLine" ADD CONSTRAINT "StockCountLine_item_fk" FOREIGN KEY ("stockItemId") REFERENCES "StockItem"("id") ON DELETE RESTRICT;
