<script lang="ts">
  import { onMount } from 'svelte';
  import { api } from '$lib/api';
  type Server = { asset: { id: string; name: string; assetTag: string | null; branchId: string | null; status: string }; environment: string; criticality: string; virtualizationRole: string; roles: { roleType: string; validFrom: string; validTo: string | null }[] };
  type Circuit = { id: string; providerName: string; circuitLabel: string; serviceType: string; status: string; downloadMbps: string; uploadMbps: string };
  let servers = $state<Server[]>([]); let circuits = $state<Circuit[]>([]); let loading = $state(true); let error = $state('');
  async function load() { loading = true; error = ''; try { const [serverData, circuitData] = await Promise.all([api.get<{ items: Server[] }>('/api/servers'), api.get<{ items: Circuit[] }>('/api/isp-circuits')]); servers = serverData.items; circuits = circuitData.items; } catch (e) { error = (e as Error).message; } finally { loading = false; } }
  onMount(load);
</script>
<svelte:head><title>Servers and connectivity — Oracle Inventory</title></svelte:head>
<div class="page"><header><h1>Servers and connectivity</h1><p>Branch-scoped infrastructure metadata. Credentials, firewall rules, and raw configurations are never displayed.</p></header>{#if loading}<div class="panel" role="status" aria-live="polite">Loading infrastructure inventory…</div>{:else if error}<div class="panel error" role="alert"><strong>Infrastructure inventory unavailable.</strong><p>{error}</p><button onclick={load}>Retry</button></div>{:else}<section class="panel" aria-labelledby="assets-heading"><h2 id="assets-heading">Server profiles</h2>{#if servers.length === 0}<p class="muted">No server profiles are available in your authorized scope.</p>{:else}<div class="table-wrap"><table><caption class="sr-only">Typed server profiles</caption><thead><tr><th scope="col">Asset</th><th scope="col">Environment</th><th scope="col">Criticality</th><th scope="col">Virtualization</th><th scope="col">Status</th></tr></thead><tbody>{#each servers as server}<tr><td>{server.asset.name}<small>{server.asset.assetTag ?? 'No asset tag'}</small></td><td>{server.environment}</td><td>{server.criticality}</td><td>{server.virtualizationRole}</td><td>{server.asset.status}</td></tr>{/each}</tbody></table></div>{/if}</section><section class="panel" aria-labelledby="circuits-heading"><h2 id="circuits-heading">ISP circuits</h2>{#if circuits.length === 0}<p class="muted">No circuits are available in your authorized scope.</p>{:else}<div class="table-wrap"><table><caption class="sr-only">ISP circuits</caption><thead><tr><th scope="col">Provider</th><th scope="col">Circuit</th><th scope="col">Service</th><th scope="col">Speed</th><th scope="col">Status</th></tr></thead><tbody>{#each circuits as circuit}<tr><td>{circuit.providerName}</td><td>{circuit.circuitLabel}</td><td>{circuit.serviceType}</td><td>{circuit.downloadMbps}/{circuit.uploadMbps} Mbps</td><td>{circuit.status}</td></tr>{/each}</tbody></table></div>{/if}</section>{/if}</div>
<style>.page{max-width:1100px;margin:0 auto;padding:32px}h1{margin:0}header p,.muted{color:var(--muted-foreground,#71717a)}.panel{border:1px solid var(--border,#e4e4e7);border-radius:10px;padding:20px;margin:16px 0}.error{color:#b91c1c}.error button{border:1px solid currentColor;border-radius:7px;background:transparent;padding:8px 12px;color:inherit;cursor:pointer}.table-wrap{overflow:auto}table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:11px;border-bottom:1px solid var(--border,#e4e4e7)}td small{display:block;color:var(--muted-foreground,#71717a);margin-top:3px}.sr-only{position:absolute;width:1px;height:1px;padding:0;margin:-1px;overflow:hidden;clip:rect(0,0,0,0);white-space:nowrap;border:0}</style>
