<script lang="ts">
  import { onMount } from 'svelte';
  import { api } from '$lib/api';
  type Asset = { id: string; name: string; assetTag: string | null; category?: { name: string } | null; branchId: string | null; status: string };
  type Circuit = { id: string; providerName: string; circuitLabel: string; serviceType: string; status: string; downloadMbps: string; uploadMbps: string };
  let assets = $state<Asset[]>([]); let circuits = $state<Circuit[]>([]); let loading = $state(true); let error = $state('');
  onMount(async () => { try { assets = await api.get<Asset[]>('/api/assets'); circuits = (await api.get<{ items: Circuit[] }>('/api/isp-circuits')).items; } catch (e) { error = (e as Error).message; } finally { loading = false; } });
  let infrastructure = $derived(assets.filter((asset) => /server|firewall|router|modem|ont/i.test(asset.category?.name ?? asset.name)));
</script>
<svelte:head><title>Servers and connectivity — Oracle Inventory</title></svelte:head>
<div class="page"><header><h1>Servers and connectivity</h1><p>Branch-scoped infrastructure metadata. Credentials, firewall rules, and raw configurations are never displayed.</p></header>{#if loading}<div class="panel" role="status">Loading infrastructure inventory…</div>{:else if error}<div class="panel error" role="alert">{error}</div>{:else}<section class="panel" aria-labelledby="assets-heading"><h2 id="assets-heading">Server, firewall, and equipment assets</h2>{#if infrastructure.length === 0}<p class="muted">No typed infrastructure assets are available in your scope.</p>{:else}<div class="table-wrap"><table><caption class="sr-only">Infrastructure assets</caption><thead><tr><th scope="col">Asset</th><th scope="col">Category</th><th scope="col">Tag</th><th scope="col">Status</th></tr></thead><tbody>{#each infrastructure as asset}<tr><td>{asset.name}</td><td>{asset.category?.name ?? 'Uncategorized'}</td><td>{asset.assetTag ?? '—'}</td><td>{asset.status}</td></tr>{/each}</tbody></table></div>{/if}</section><section class="panel" aria-labelledby="circuits-heading"><h2 id="circuits-heading">ISP circuits</h2>{#if circuits.length === 0}<p class="muted">No circuits are available, or the infrastructure feature is disabled for this branch.</p>{:else}<div class="table-wrap"><table><caption class="sr-only">ISP circuits</caption><thead><tr><th scope="col">Provider</th><th scope="col">Circuit</th><th scope="col">Service</th><th scope="col">Speed</th><th scope="col">Status</th></tr></thead><tbody>{#each circuits as circuit}<tr><td>{circuit.providerName}</td><td>{circuit.circuitLabel}</td><td>{circuit.serviceType}</td><td>{circuit.downloadMbps}/{circuit.uploadMbps} Mbps</td><td>{circuit.status}</td></tr>{/each}</tbody></table></div>{/if}</section>{/if}</div>
<style>.page{max-width:1100px;margin:0 auto;padding:32px}h1{margin:0}header p,.muted{color:var(--muted-foreground,#71717a)}.panel{border:1px solid var(--border,#e4e4e7);border-radius:10px;padding:20px;margin:16px 0}.error{color:#b91c1c}.table-wrap{overflow:auto}table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:11px;border-bottom:1px solid var(--border,#e4e4e7)}.sr-only{position:absolute;width:1px;height:1px;padding:0;margin:-1px;overflow:hidden;clip:rect(0,0,0,0);white-space:nowrap;border:0}</style>
