-- Phase 5 additive infrastructure metadata. Preflight duplicate temporal rows before applying.
CREATE TYPE "ServerEnvironment" AS ENUM ('production','staging','development','test','other');
CREATE TYPE "Criticality" AS ENUM ('critical','high','medium','low');
CREATE TYPE "VirtualizationRole" AS ENUM ('physical','hypervisor','virtual_machine','container_host','other');
CREATE TYPE "ServerRoleType" AS ENUM ('domain_controller','file_server','application_server','database_server','backup_server','dns_server','dhcp_server','other');
CREATE TYPE "FirewallDeploymentMode" AS ENUM ('routed_gateway','transparent_bridge','host_firewall','virtual_appliance','other');
CREATE TYPE "FirewallHaRole" AS ENUM ('standalone','active','passive','member','unknown');
CREATE TYPE "IspServiceType" AS ENUM ('fiber','dsl','cable','wireless','leased_line','satellite','other');
CREATE TYPE "IspCircuitStatus" AS ENUM ('planned','active','degraded','suspended','terminated');
CREATE TYPE "IspAddressingMode" AS ENUM ('static','dhcp','dynamic','pppoe','cgnat','unknown');
CREATE TYPE "CircuitEquipmentRole" AS ENUM ('ont','modem','router','firewall');

CREATE TABLE "ServerProfile" ("id" TEXT NOT NULL,"assetId" TEXT NOT NULL,"environment" "ServerEnvironment" NOT NULL,"criticality" "Criticality" NOT NULL,"virtualizationRole" "VirtualizationRole" NOT NULL,"serviceOwner" TEXT NOT NULL,"supportOwner" TEXT,"purpose" TEXT,"idempotencyKey" TEXT,"idempotencyPayloadHash" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "ServerProfile_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "ServerProfile_assetId_key" ON "ServerProfile"("assetId"); CREATE UNIQUE INDEX "ServerProfile_idempotencyKey_key" ON "ServerProfile"("idempotencyKey");
ALTER TABLE "ServerProfile" ADD CONSTRAINT "ServerProfile_assetId_fkey" FOREIGN KEY ("assetId") REFERENCES "Asset"("id") ON DELETE CASCADE ON UPDATE CASCADE;
CREATE TABLE "ServerRoleAssignment" ("id" TEXT NOT NULL,"serverId" TEXT NOT NULL,"roleType" "ServerRoleType" NOT NULL,"roleName" TEXT,"domainName" TEXT,"isPrimary" BOOLEAN NOT NULL DEFAULT false,"validFrom" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"validTo" TIMESTAMP(3),"notes" TEXT,"idempotencyKey" TEXT,"idempotencyPayloadHash" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "ServerRoleAssignment_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "ServerRoleAssignment_idempotencyKey_key" ON "ServerRoleAssignment"("idempotencyKey"); CREATE INDEX "ServerRoleAssignment_serverId_validFrom_idx" ON "ServerRoleAssignment"("serverId","validFrom");
ALTER TABLE "ServerRoleAssignment" ADD CONSTRAINT "ServerRoleAssignment_serverId_fkey" FOREIGN KEY ("serverId") REFERENCES "ServerProfile"("id") ON DELETE CASCADE ON UPDATE CASCADE;
CREATE TABLE "FirewallProfile" ("id" TEXT NOT NULL,"assetId" TEXT NOT NULL,"deploymentMode" "FirewallDeploymentMode" NOT NULL,"haRole" "FirewallHaRole" NOT NULL,"policyOwner" TEXT NOT NULL,"managementInterfaceId" TEXT,"configurationArtifactRef" TEXT,"idempotencyKey" TEXT,"idempotencyPayloadHash" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "FirewallProfile_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "FirewallProfile_assetId_key" ON "FirewallProfile"("assetId"); CREATE UNIQUE INDEX "FirewallProfile_idempotencyKey_key" ON "FirewallProfile"("idempotencyKey");
ALTER TABLE "FirewallProfile" ADD CONSTRAINT "FirewallProfile_assetId_fkey" FOREIGN KEY ("assetId") REFERENCES "Asset"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "FirewallProfile" ADD CONSTRAINT "FirewallProfile_managementInterfaceId_fkey" FOREIGN KEY ("managementInterfaceId") REFERENCES "NetworkInterface"("id") ON DELETE SET NULL ON UPDATE CASCADE;
CREATE TABLE "IspCircuit" ("id" TEXT NOT NULL,"branchId" TEXT NOT NULL,"providerName" TEXT NOT NULL,"circuitLabel" TEXT NOT NULL,"serviceType" "IspServiceType" NOT NULL,"status" "IspCircuitStatus" NOT NULL,"demarcLocation" TEXT,"downloadMbps" DECIMAL(65,30) NOT NULL,"uploadMbps" DECIMAL(65,30) NOT NULL,"addressingMode" "IspAddressingMode" NOT NULL,"activatedAt" TIMESTAMP(3),"terminatedAt" TIMESTAMP(3),"providerCircuitIdMasked" TEXT,"idempotencyKey" TEXT,"idempotencyPayloadHash" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "IspCircuit_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "IspCircuit_idempotencyKey_key" ON "IspCircuit"("idempotencyKey"); CREATE INDEX "IspCircuit_branchId_status_idx" ON "IspCircuit"("branchId","status"); ALTER TABLE "IspCircuit" ADD CONSTRAINT "IspCircuit_branchId_fkey" FOREIGN KEY ("branchId") REFERENCES "Branch"("id") ON DELETE CASCADE ON UPDATE CASCADE;
CREATE TABLE "CircuitEquipmentAssignment" ("id" TEXT NOT NULL,"circuitId" TEXT NOT NULL,"assetId" TEXT NOT NULL,"role" "CircuitEquipmentRole" NOT NULL,"validFrom" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"validTo" TIMESTAMP(3),"idempotencyKey" TEXT,"idempotencyPayloadHash" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "CircuitEquipmentAssignment_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "CircuitEquipmentAssignment_idempotencyKey_key" ON "CircuitEquipmentAssignment"("idempotencyKey"); CREATE INDEX "CircuitEquipmentAssignment_circuitId_validFrom_idx" ON "CircuitEquipmentAssignment"("circuitId","validFrom"); ALTER TABLE "CircuitEquipmentAssignment" ADD CONSTRAINT "CircuitEquipmentAssignment_circuitId_fkey" FOREIGN KEY ("circuitId") REFERENCES "IspCircuit"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "CircuitEquipmentAssignment" ADD CONSTRAINT "CircuitEquipmentAssignment_assetId_fkey" FOREIGN KEY ("assetId") REFERENCES "Asset"("id") ON DELETE CASCADE ON UPDATE CASCADE;
CREATE TABLE "IspCircuitAddress" ("id" TEXT NOT NULL,"circuitId" TEXT NOT NULL,"address" TEXT NOT NULL,"prefixLength" INTEGER NOT NULL,"gateway" TEXT,"validFrom" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"validTo" TIMESTAMP(3),"idempotencyKey" TEXT,"idempotencyPayloadHash" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "IspCircuitAddress_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "IspCircuitAddress_idempotencyKey_key" ON "IspCircuitAddress"("idempotencyKey"); CREATE INDEX "IspCircuitAddress_circuitId_validFrom_idx" ON "IspCircuitAddress"("circuitId","validFrom"); ALTER TABLE "IspCircuitAddress" ADD CONSTRAINT "IspCircuitAddress_circuitId_fkey" FOREIGN KEY ("circuitId") REFERENCES "IspCircuit"("id") ON DELETE CASCADE ON UPDATE CASCADE;
CREATE TABLE "IspCircuitSecretReference" ("id" TEXT NOT NULL,"circuitId" TEXT NOT NULL,"secretReferenceId" TEXT NOT NULL,"purpose" TEXT,"idempotencyKey" TEXT,"idempotencyPayloadHash" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "IspCircuitSecretReference_pkey" PRIMARY KEY ("id"));
CREATE UNIQUE INDEX "IspCircuitSecretReference_circuitId_secretReferenceId_key" ON "IspCircuitSecretReference"("circuitId","secretReferenceId"); ALTER TABLE "IspCircuitSecretReference" ADD CONSTRAINT "IspCircuitSecretReference_circuitId_fkey" FOREIGN KEY ("circuitId") REFERENCES "IspCircuit"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "IspCircuitSecretReference" ADD CONSTRAINT "IspCircuitSecretReference_secretReferenceId_fkey" FOREIGN KEY ("secretReferenceId") REFERENCES "SecretReference"("id") ON DELETE CASCADE ON UPDATE CASCADE;
