<script lang="ts">
  import { api } from '$lib/api';
  const featureDisabled = true;
  const modes = ['routed_gateway', 'transparent_bridge', 'host_firewall', 'virtual_appliance', 'other'] as const;
  const roles = ['standalone', 'active', 'passive', 'member', 'unknown'] as const;
  let assetId = $state(''); let deploymentMode = $state('routed_gateway'); let haRole = $state('standalone'); let policyOwner = $state(''); let managementInterfaceId = $state(''); let configurationArtifactRef = $state(''); let saving = $state(false); let error = $state(''); let saved = $state(false);
  async function submit() { error = ''; saved = false; if (!assetId.trim() || !policyOwner.trim()) { error = 'An existing firewall Asset ID and policy owner are required.'; return; } saving = true; try { await api.put(`/api/firewalls/${encodeURIComponent(assetId.trim())}/profile`, { deploymentMode, haRole, policyOwner: policyOwner.trim(), managementInterfaceId: managementInterfaceId.trim() || undefined, configurationArtifactRef: configurationArtifactRef.trim() || undefined }); saved = true; } catch (caught) { error = caught instanceof Error ? caught.message : 'Unable to save firewall profile.'; } finally { saving = false; } }
</script>
<svelte:head><title>Firewall intake — Oracle Inventory</title></svelte:head>
<div class="page"><a href="/infrastructure/firewalls" class="back">← Firewalls</a><header><p class="eyebrow">Manual intake</p><h1>Firewall profile</h1><p>Record governance metadata only. Never enter passwords, VPN/PPPoE values, rulesets, or raw firewall configuration.</p></header><section class="notice" role="status"><strong>Temporarily disabled</strong><p>Phase 5 remains fail-closed until the migration, permission review, and rollout are approved.</p></section><form class="card" onsubmit={(event) => { event.preventDefault(); submit(); }}><fieldset disabled={featureDisabled || saving}><legend>Firewall metadata</legend><label for="asset-id">Existing firewall Asset ID <span aria-hidden="true">*</span></label><input id="asset-id" bind:value={assetId} autocomplete="off" placeholder="Asset ID" /><div class="two-up"><label for="mode">Deployment mode<select id="mode" bind:value={deploymentMode}>{#each modes as item}<option value={item}>{item}</option>{/each}</select></label><label for="ha-role">HA role<select id="ha-role" bind:value={haRole}>{#each roles as item}<option value={item}>{item}</option>{/each}</select></label></div><label for="owner">Policy owner <span aria-hidden="true">*</span><input id="owner" bind:value={policyOwner} maxlength="160" /></label><label for="interface">Management interface ID <span class="optional">(metadata reference)</span><input id="interface" bind:value={managementInterfaceId} autocomplete="off" /></label><label for="artifact">Configuration artifact reference <span class="optional">(repo:// or vault:// reference only)</span><input id="artifact" bind:value={configurationArtifactRef} maxlength="240" /></label><button type="submit">{saving ? 'Saving…' : 'Save firewall profile'}</button></fieldset>{#if error}<p class="error" role="alert">{error}</p>{/if}{#if saved}<p class="success" role="status">Firewall profile saved.</p>{/if}</form></div>
<style>.page{max-width:760px;margin:0 auto;padding:32px 24px 48px}.back{color:var(--body);text-decoration:none}.eyebrow{margin:24px 0 5px;color:var(--mute);font-size:12px;font-weight:700;letter-spacing:.08em;text-transform:uppercase}h1{margin:0;color:var(--ink);font-size:32px}header p:last-child{color:var(--body)}.card,.notice{border:1px solid var(--hairline);border-radius:12px;background:var(--canvas);padding:24px;margin-top:18px}.notice{border-color:#d6a400;background:color-mix(in srgb,#d6a400 8%,var(--canvas))}.notice p{margin-bottom:0}.card fieldset{border:0;padding:0;margin:0}.card legend{font-size:18px;font-weight:700}label{display:block;margin:18px 0 6px;font-weight:650}input,select{box-sizing:border-box;width:100%;border:1px solid var(--hairline);border-radius:8px;padding:10px 12px;background:var(--canvas);color:var(--ink);font:inherit}.two-up{display:grid;grid-template-columns:1fr 1fr;gap:16px}.optional{color:var(--mute);font-weight:400}button{margin-top:22px;border:0;border-radius:8px;padding:10px 14px;background:var(--ink);color:var(--on-primary);font:inherit;font-weight:650}fieldset:disabled input,fieldset:disabled select,button:disabled{opacity:.55;cursor:not-allowed}.error{color:var(--error)}.success{color:var(--success,#15803d)}@media(max-width:640px){.page{padding:24px 16px}.two-up{grid-template-columns:1fr}}
</style>
