<script lang="ts">
  import { onMount } from 'svelte'; import { api } from '$lib/api';
  type Asset = { id: string; name: string; assetTag?: string | null; category?: { name?: string } }; let assets: Asset[] = [], assetId = '', updatedAt = '', deploymentMode = 'routed_gateway', haRole = 'standalone', policyOwner = '', review = false, status = '', error = '', loading = true;
  async function load() { loading = true; error = ''; try { const result = await api.get<{ items?: Asset[] } | Asset[]>('/api/assets'); assets = (Array.isArray(result) ? result : result.items ?? []).filter((asset) => /firewall/i.test(asset.category?.name ?? '')); } catch (e) { error = (e as Error).message; } finally { loading = false; } } onMount(load);
  async function selectAsset() { updatedAt = ''; if (!assetId) return; try { const profile = await api.get<{ updatedAt?: string; deploymentMode?: string; haRole?: string; policyOwner?: string } | null>(`/api/firewalls/${assetId}/profile`); if (profile) { updatedAt = profile.updatedAt ?? ''; deploymentMode = profile.deploymentMode ?? deploymentMode; haRole = profile.haRole ?? haRole; policyOwner = profile.policyOwner ?? policyOwner; } } catch (e) { error = (e as Error).message; } }
  let previousAsset = ''; $effect(() => { if (assetId && assetId !== previousAsset) { previousAsset = assetId; selectAsset(); } });
  const payload = () => ({ asset: assets.find((item) => item.id === assetId)?.name ?? assetId, deploymentMode, haRole, policyOwner, updatedAt: updatedAt || 'new profile' });
  async function save() { error = ''; try { await api.put(`/api/firewalls/${assetId}/profile`, { deploymentMode, haRole, policyOwner, ...(updatedAt ? { expectedUpdatedAt: updatedAt } : {}) }); status = 'Firewall profile saved.'; review = false; } catch (e) { if ((e as Error).message.includes('changed')) { await selectAsset(); review = true; error = 'The profile changed. Values were refreshed; review and confirm again.'; } else error = (e as Error).message; } }
</script>
<svelte:head><title>Firewall intake</title></svelte:head><div class="page"><h1>Firewall intake</h1><p>Rules, passwords, VPN keys, and raw configuration are never stored.</p>{#if loading}<section class="panel" role="status">Loading authorized firewall assets…</section>{:else if error && !review}<section class="panel" role="alert"><p class="error">{error}</p><button onclick={load}>Retry</button></section>{:else if review}<section class="panel"><h2>Review before saving</h2><dl>{#each Object.entries(payload()) as [key, value]}<div><dt>{key}</dt><dd>{value || '—'}</dd></div>{/each}</dl><p>Management-interface and sensitive-field permissions are enforced by the API.</p><button onclick={save} disabled={!assetId}>Confirm and save</button><button class="secondary" onclick={() => review = false}>Back to edit</button></section>{:else}<section class="panel">{#if assets.length === 0}<p>No authorized Firewall-category assets are available.</p>{:else}<label for="asset">Firewall asset</label><select id="asset" bind:value={assetId}><option value="">Select an authorized firewall</option>{#each assets as asset}<option value={asset.id}>{asset.name} · {asset.assetTag ?? 'No tag'}</option>{/each}</select><label for="mode">Deployment mode</label><select id="mode" bind:value={deploymentMode}><option>routed_gateway</option><option>transparent_bridge</option><option>host_firewall</option><option>virtual_appliance</option><option>other</option></select><label for="ha">HA role</label><select id="ha" bind:value={haRole}><option>standalone</option><option>active</option><option>passive</option><option>member</option><option>unknown</option></select><label for="owner">Policy owner</label><input id="owner" bind:value={policyOwner}/><button onclick={() => review = true} disabled={!assetId}>Review firewall profile</button>{/if}</section>{/if}{#if error && review}<p role="alert" class="error">{error}</p>{/if}{#if status}<p role="status" class="ok">{status}</p>{/if}</div><style>.page{max-width:700px;margin:0 auto;padding:32px}.panel{border:1px solid #ddd;border-radius:10px;padding:20px}label{display:block;margin:12px 0 5px;font-weight:600}input,select{display:block;width:100%;padding:8px}.error{color:#b91c1c}.ok{color:#166534}button{margin-top:18px;padding:10px 14px}.secondary{margin-left:8px}</style>
