<script lang="ts">
  import { onMount } from 'svelte'; import { api } from '$lib/api';
  type Item = { id: string; sku: string; name: string; unitOfMeasure: string; balance: number }; type Entry = { movement: { movementType: string; createdAt: string }; locationId: string; quantityDelta: string };
  let catalog: Item[] = [], selected = '', entries: Entry[] = [], loading = true, loadingHistory = false, error = '';
  async function loadItems() { try { catalog = (await api.get<{ items: Item[] }>('/api/stock/items?page=1&pageSize=100')).items; } catch (e) { error = (e as Error).message; } finally { loading = false; } }
  async function loadHistory() { if (!selected) { entries = []; return; } loadingHistory = true; error = ''; try { entries = (await api.get<{ items: Entry[] }>(`/api/stock/items/${selected}/movements?page=1&pageSize=100`)).items; } catch (e) { error = (e as Error).message; } finally { loadingHistory = false; } }
  onMount(loadItems);
</script>
<div class="page"><h1>Stock movements</h1><p>Immutable ledger history. Corrections use compensating movements.</p>{#if loading}<section role="status">Loading authorized stock items…</section>{:else}<section class="panel"><label for="item">Stock item</label><select id="item" bind:value={selected} onchange={loadHistory}><option value="">Select an item</option>{#each catalog as item}<option value={item.id}>{item.sku} · {item.name} ({item.balance} {item.unitOfMeasure})</option>{/each}</select>{#if !catalog.length}<p>No authorized stock items are available.</p>{/if}</section>{#if error}<p role="alert" class="error">{error}</p>{:else if loadingHistory}<p role="status">Loading movement history…</p>{:else if selected && !entries.length}<section class="panel">No movement history is available for this item.</section>{:else if entries.length}<section class="panel"><table><caption>Movement ledger history</caption><thead><tr><th scope="col">Movement</th><th scope="col">Location</th><th scope="col">Delta</th><th scope="col">Created</th></tr></thead><tbody>{#each entries as item}<tr><td>{item.movement.movementType}</td><td>{item.locationId}</td><td>{item.quantityDelta}</td><td>{item.movement.createdAt}</td></tr>{/each}</tbody></table></section>{/if}{/if}</div><style>.page{max-width:900px;margin:auto;padding:32px}.panel{border:1px solid #ddd;border-radius:10px;padding:20px;margin:16px 0}label{display:block;font-weight:600}select{width:100%;padding:9px;margin-top:6px}table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:8px;border-bottom:1px solid #ddd}.error{color:#b91c1c}</style>
