-- Generated by: supabase migration new phase5_secret_idempotency_fix
-- Provenance: semantically aligned with oracle-api/prisma/migrations/20260823110000_phase5_secret_idempotency_fix/migration.sql
-- Scope: unique replay key for circuit secret-reference links.
-- Authored only. NOT applied by this agent. Apply via the standard Supabase migration deploy pipeline.

CREATE UNIQUE INDEX "IspCircuitSecretReference_idempotencyKey_key" ON "IspCircuitSecretReference"("idempotencyKey");
