-- Generated by: supabase migration new phase1_computer_intake
-- Provenance: semantically aligned with oracle-api/prisma/migrations/20260822120000_computer_intake/migration.sql
-- Scope: additive Phase 1 computer manual intake only. No automatic tag rewrite or merge.

ALTER TABLE public."Asset" ADD COLUMN "purchaseDate" TIMESTAMP(3);

-- Read-only preflight is represented by this guard. Resolve the report manually before applying.
DO $$
BEGIN
  IF EXISTS (
    SELECT lower(btrim("assetTag"))
    FROM public."Asset"
    WHERE "assetTag" IS NOT NULL AND btrim("assetTag") <> ''
    GROUP BY lower(btrim("assetTag"))
    HAVING count(*) > 1
  ) THEN
    RAISE EXCEPTION 'Computer intake migration blocked: duplicate nonblank normalized asset tags require manual review';
  END IF;
END $$;

CREATE UNIQUE INDEX "Asset_assetTag_nonblank_unique"
  ON public."Asset" (lower(btrim("assetTag")))
  WHERE "assetTag" IS NOT NULL AND btrim("assetTag") <> '';

DO $$ BEGIN CREATE TYPE public."DeviceType" AS ENUM ('computer', 'laptop'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE public."ComponentType" AS ENUM ('ram', 'storage'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE public."ObservationStatus" AS ENUM ('proposed', 'verified', 'conflict', 'rejected'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE public."DraftStatus" AS ENUM ('draft', 'submitted', 'cancelled'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE TABLE public."DeviceProfile" (
  "id" TEXT NOT NULL,
  "assetId" TEXT NOT NULL,
  "deviceType" public."DeviceType" NOT NULL DEFAULT 'computer',
  "brand" TEXT, "model" TEXT, "deviceSerial" TEXT, "processor" TEXT,
  "motherboard" TEXT, "operatingSystem" TEXT, "osVersion" TEXT,
  "osInstallDate" TIMESTAMP(3), "source" TEXT NOT NULL DEFAULT 'manual',
  "sourceObservedAt" TIMESTAMP(3), "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "DeviceProfile_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "DeviceProfile_assetId_key" ON public."DeviceProfile"("assetId");
CREATE INDEX "DeviceProfile_deviceType_idx" ON public."DeviceProfile"("deviceType");

CREATE TABLE public."AssetComponent" (
  "id" TEXT NOT NULL, "assetId" TEXT NOT NULL, "deviceProfileId" TEXT,
  "type" public."ComponentType" NOT NULL, "slotOrBay" TEXT, "brand" TEXT,
  "model" TEXT, "serialNumber" TEXT, "capacity" TEXT, "storageKind" TEXT,
  "source" TEXT NOT NULL DEFAULT 'manual', "sourceObservedAt" TIMESTAMP(3),
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "AssetComponent_pkey" PRIMARY KEY ("id")
);
CREATE INDEX "AssetComponent_assetId_type_idx" ON public."AssetComponent"("assetId", "type");

CREATE TABLE public."InventoryObservation" (
  "id" TEXT NOT NULL, "assetId" TEXT NOT NULL, "source" TEXT NOT NULL,
  "status" public."ObservationStatus" NOT NULL DEFAULT 'proposed', "fields" JSONB NOT NULL,
  "observedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "reviewedById" TEXT,
  "reviewedAt" TIMESTAMP(3), "reviewNotes" TEXT,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "InventoryObservation_pkey" PRIMARY KEY ("id")
);
CREATE INDEX "InventoryObservation_assetId_status_idx" ON public."InventoryObservation"("assetId", "status");

CREATE TABLE public."ComputerIntakeDraft" (
  "id" TEXT NOT NULL, "createdById" TEXT NOT NULL, "branchId" TEXT,
  "status" public."DraftStatus" NOT NULL DEFAULT 'draft', "data" JSONB NOT NULL,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL,
  "submittedAt" TIMESTAMP(3), "submittedAssetId" TEXT,
  "submitIdempotencyKey" TEXT, "submitPayloadHash" TEXT,
  CONSTRAINT "ComputerIntakeDraft_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "ComputerIntakeDraft_submitIdempotencyKey_key" ON public."ComputerIntakeDraft"("submitIdempotencyKey");
CREATE INDEX "ComputerIntakeDraft_createdById_status_idx" ON public."ComputerIntakeDraft"("createdById", "status");
CREATE INDEX "ComputerIntakeDraft_branchId_status_idx" ON public."ComputerIntakeDraft"("branchId", "status");

ALTER TABLE public."DeviceProfile" ADD CONSTRAINT "DeviceProfile_assetId_fkey" FOREIGN KEY ("assetId") REFERENCES public."Asset"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE public."AssetComponent" ADD CONSTRAINT "AssetComponent_assetId_fkey" FOREIGN KEY ("assetId") REFERENCES public."Asset"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE public."AssetComponent" ADD CONSTRAINT "AssetComponent_deviceProfileId_fkey" FOREIGN KEY ("deviceProfileId") REFERENCES public."DeviceProfile"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE public."InventoryObservation" ADD CONSTRAINT "InventoryObservation_assetId_fkey" FOREIGN KEY ("assetId") REFERENCES public."Asset"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE public."InventoryObservation" ADD CONSTRAINT "InventoryObservation_reviewedById_fkey" FOREIGN KEY ("reviewedById") REFERENCES public."SystemUser"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE public."ComputerIntakeDraft" ADD CONSTRAINT "ComputerIntakeDraft_createdById_fkey" FOREIGN KEY ("createdById") REFERENCES public."SystemUser"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE public."ComputerIntakeDraft" ADD CONSTRAINT "ComputerIntakeDraft_branchId_fkey" FOREIGN KEY ("branchId") REFERENCES public."Branch"("id") ON DELETE SET NULL ON UPDATE CASCADE;

ALTER TABLE public."DeviceProfile" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."AssetComponent" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."InventoryObservation" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."ComputerIntakeDraft" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public."DeviceProfile", public."AssetComponent", public."InventoryObservation", public."ComputerIntakeDraft" FROM anon, authenticated;
REVOKE ALL ON TABLE public."DeviceProfile", public."AssetComponent", public."InventoryObservation", public."ComputerIntakeDraft" FROM PUBLIC;

