-- Generated by: supabase migration new phase5_shared_policy_and_address_overlap
-- Provenance: semantically aligned with oracle-api/prisma/migrations/20260823140000_phase5_shared_policy_and_address_overlap/migration.sql
-- Scope: forward-only hardening. NULL/false is the safe default for existing rows.
-- Authored only. NOT applied by this agent. Apply via the standard Supabase migration deploy pipeline.

ALTER TABLE "CircuitEquipmentAssignment" ADD COLUMN "sharedServiceApproved" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "CircuitEquipmentAssignment" ADD COLUMN "sharedServiceReason" TEXT;

-- PostgreSQL exclusion constraints are intentionally not applied here because existing deployments may
-- not have btree_gist installed. The API uses a serializable transaction and overlap predicate; operators
-- may add an exclusion constraint after reviewing existing rows:
-- CREATE EXTENSION IF NOT EXISTS btree_gist;
-- ALTER TABLE "IspCircuitAddress" ADD CONSTRAINT "IspCircuitAddress_no_overlap"
-- EXCLUDE USING gist ("circuitId" WITH =, tstzrange("validFrom", COALESCE("validTo", 'infinity'::timestamp), '[)') WITH &&);
