-- Generated by: supabase migration new phase3_network_infrastructure
-- Provenance: semantically aligned with oracle-api/prisma/migrations/20260822150000_network_infrastructure/migration.sql
-- Scope: additive Phase 3 network infrastructure inventory only (interfaces, IP observations, VLANs, ports, port connections).
-- Authored only. NOT applied by this agent. Apply via the standard Supabase migration deploy pipeline.

DO $$ BEGIN CREATE TYPE public."IpAddressFamily" AS ENUM ('ipv4', 'ipv6'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE public."AddressingMode" AS ENUM ('static', 'dhcp', 'dynamic', 'unknown'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE public."VlanTaggingMode" AS ENUM ('access', 'tagged', 'trunk'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE public."PortStatus" AS ENUM ('up', 'down', 'disabled', 'unknown'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE public."LinkType" AS ENUM ('physical', 'logical', 'wan'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE TABLE public."NetworkInterface" (
  "id" TEXT NOT NULL, "assetId" TEXT NOT NULL, "interfaceName" TEXT NOT NULL,
  "macAddress" TEXT, "description" TEXT,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL,
  "idempotencyKey" TEXT, "idempotencyPayloadHash" TEXT,
  CONSTRAINT "NetworkInterface_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "NetworkInterface_assetId_interfaceName_key" ON public."NetworkInterface"("assetId", "interfaceName");
CREATE UNIQUE INDEX "NetworkInterface_idempotencyKey_key" ON public."NetworkInterface"("idempotencyKey");
CREATE INDEX "NetworkInterface_macAddress_idx" ON public."NetworkInterface"("macAddress");

CREATE TABLE public."IpAddressObservation" (
  "id" TEXT NOT NULL, "interfaceId" TEXT NOT NULL, "address" TEXT NOT NULL, "prefixLength" INTEGER NOT NULL,
  "family" public."IpAddressFamily" NOT NULL, "addressingMode" public."AddressingMode" NOT NULL,
  "gateway" TEXT, "dnsServers" TEXT[] NOT NULL, "source" TEXT NOT NULL,
  "observedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "validFrom" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "validTo" TIMESTAMP(3), "idempotencyKey" TEXT, "idempotencyPayloadHash" TEXT,
  CONSTRAINT "IpAddressObservation_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "IpAddressObservation_idempotencyKey_key" ON public."IpAddressObservation"("idempotencyKey");
CREATE INDEX "IpAddressObservation_interfaceId_observedAt_idx" ON public."IpAddressObservation"("interfaceId", "observedAt");
CREATE INDEX "IpAddressObservation_address_idx" ON public."IpAddressObservation"("address");

CREATE TABLE public."Vlan" (
  "id" TEXT NOT NULL, "branchId" TEXT NOT NULL, "vlanNumber" INTEGER NOT NULL, "vlanName" TEXT,
  "cidr" TEXT, "gateway" TEXT,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL,
  "idempotencyKey" TEXT, "idempotencyPayloadHash" TEXT,
  CONSTRAINT "Vlan_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "Vlan_branchId_vlanNumber_key" ON public."Vlan"("branchId", "vlanNumber");
CREATE UNIQUE INDEX "Vlan_idempotencyKey_key" ON public."Vlan"("idempotencyKey");

CREATE TABLE public."InterfaceVlanAssignment" (
  "id" TEXT NOT NULL, "interfaceId" TEXT NOT NULL, "vlanId" TEXT NOT NULL,
  "taggingMode" public."VlanTaggingMode" NOT NULL, "isNative" BOOLEAN NOT NULL DEFAULT false,
  "effectiveFrom" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "effectiveTo" TIMESTAMP(3),
  "idempotencyKey" TEXT, "idempotencyPayloadHash" TEXT,
  CONSTRAINT "InterfaceVlanAssignment_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "InterfaceVlanAssignment_idempotencyKey_key" ON public."InterfaceVlanAssignment"("idempotencyKey");
CREATE INDEX "InterfaceVlanAssignment_interfaceId_effectiveFrom_idx" ON public."InterfaceVlanAssignment"("interfaceId", "effectiveFrom");
CREATE INDEX "InterfaceVlanAssignment_vlanId_effectiveFrom_idx" ON public."InterfaceVlanAssignment"("vlanId", "effectiveFrom");

CREATE TABLE public."NetworkPort" (
  "id" TEXT NOT NULL, "assetId" TEXT NOT NULL, "portNumber" TEXT NOT NULL, "portLabel" TEXT,
  "medium" TEXT, "speedMbps" INTEGER, "poeCapability" TEXT,
  "adminStatus" public."PortStatus" NOT NULL DEFAULT 'unknown',
  "operationalStatus" public."PortStatus" NOT NULL DEFAULT 'unknown',
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL,
  "idempotencyKey" TEXT, "idempotencyPayloadHash" TEXT,
  CONSTRAINT "NetworkPort_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "NetworkPort_assetId_portNumber_key" ON public."NetworkPort"("assetId", "portNumber");
CREATE UNIQUE INDEX "NetworkPort_idempotencyKey_key" ON public."NetworkPort"("idempotencyKey");

CREATE TABLE public."PortConnection" (
  "id" TEXT NOT NULL, "fromPortId" TEXT NOT NULL, "toPortId" TEXT, "toInterfaceId" TEXT,
  "branchId" TEXT NOT NULL, "linkType" public."LinkType" NOT NULL,
  "effectiveFrom" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "effectiveTo" TIMESTAMP(3),
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "idempotencyKey" TEXT, "idempotencyPayloadHash" TEXT,
  CONSTRAINT "PortConnection_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "PortConnection_idempotencyKey_key" ON public."PortConnection"("idempotencyKey");
CREATE INDEX "PortConnection_branchId_effectiveFrom_idx" ON public."PortConnection"("branchId", "effectiveFrom");
CREATE INDEX "PortConnection_fromPortId_effectiveTo_idx" ON public."PortConnection"("fromPortId", "effectiveTo");

ALTER TABLE public."NetworkInterface" ADD CONSTRAINT "NetworkInterface_assetId_fkey" FOREIGN KEY ("assetId") REFERENCES public."Asset"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE public."IpAddressObservation" ADD CONSTRAINT "IpAddressObservation_interfaceId_fkey" FOREIGN KEY ("interfaceId") REFERENCES public."NetworkInterface"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE public."Vlan" ADD CONSTRAINT "Vlan_branchId_fkey" FOREIGN KEY ("branchId") REFERENCES public."Branch"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE public."InterfaceVlanAssignment" ADD CONSTRAINT "InterfaceVlanAssignment_interfaceId_fkey" FOREIGN KEY ("interfaceId") REFERENCES public."NetworkInterface"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE public."InterfaceVlanAssignment" ADD CONSTRAINT "InterfaceVlanAssignment_vlanId_fkey" FOREIGN KEY ("vlanId") REFERENCES public."Vlan"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE public."NetworkPort" ADD CONSTRAINT "NetworkPort_assetId_fkey" FOREIGN KEY ("assetId") REFERENCES public."Asset"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE public."PortConnection" ADD CONSTRAINT "PortConnection_fromPortId_fkey" FOREIGN KEY ("fromPortId") REFERENCES public."NetworkPort"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE public."PortConnection" ADD CONSTRAINT "PortConnection_toPortId_fkey" FOREIGN KEY ("toPortId") REFERENCES public."NetworkPort"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE public."PortConnection" ADD CONSTRAINT "PortConnection_toInterfaceId_fkey" FOREIGN KEY ("toInterfaceId") REFERENCES public."NetworkInterface"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE public."PortConnection" ADD CONSTRAINT "PortConnection_branchId_fkey" FOREIGN KEY ("branchId") REFERENCES public."Branch"("id") ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE public."NetworkInterface" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."IpAddressObservation" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."Vlan" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."InterfaceVlanAssignment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."NetworkPort" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."PortConnection" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE public."NetworkInterface", public."IpAddressObservation", public."Vlan", public."InterfaceVlanAssignment", public."NetworkPort", public."PortConnection" FROM anon, authenticated;
REVOKE ALL ON TABLE public."NetworkInterface", public."IpAddressObservation", public."Vlan", public."InterfaceVlanAssignment", public."NetworkPort", public."PortConnection" FROM PUBLIC;

INSERT INTO public."Permission" ("id", "key", "description") VALUES
  ('perm-manage-infrastructure-assets', 'manage_infrastructure_assets', 'Manage network and infrastructure inventory'),
  ('perm-view-sensitive-network-fields', 'view_sensitive_network_fields', 'View sensitive network addressing and topology fields')
ON CONFLICT ("id") DO UPDATE SET "key" = EXCLUDED."key", "description" = EXCLUDED."description";
INSERT INTO public."RolePermission" ("roleId", "permissionId") VALUES
  ('role-super-admin', 'perm-manage-infrastructure-assets'),
  ('role-admin', 'perm-manage-infrastructure-assets'),
  ('role-super-admin', 'perm-view-sensitive-network-fields'),
  ('role-admin', 'perm-view-sensitive-network-fields')
ON CONFLICT ("roleId", "permissionId") DO NOTHING;
