-- Generated by: supabase migration new peripheral_component_types
-- Provenance: semantically aligned with oracle-api/prisma/migrations/20260825160000_peripheral_component_types/migration.sql
-- Scope: peripheral component types (Monitor, Keyboard, Mouse, Speaker, Webcam,
-- Microphone, Printer, UPS, AVR, Clicker, Projector, TV, Signal Booster,
-- Flash Drive, External HDD, HDD/SSD and NVME/SSD docking stations) reuse
-- AssetComponent as child rows on a parent asset, same pattern as the
-- RAM/Storage rows already built for Computer intake.
-- Authored only. NOT applied by this agent. Apply via the standard Supabase migration deploy pipeline.

ALTER TYPE "ComponentType" ADD VALUE IF NOT EXISTS 'monitor';
ALTER TYPE "ComponentType" ADD VALUE IF NOT EXISTS 'keyboard';
ALTER TYPE "ComponentType" ADD VALUE IF NOT EXISTS 'mouse';
ALTER TYPE "ComponentType" ADD VALUE IF NOT EXISTS 'speaker';
ALTER TYPE "ComponentType" ADD VALUE IF NOT EXISTS 'webcam';
ALTER TYPE "ComponentType" ADD VALUE IF NOT EXISTS 'microphone';
ALTER TYPE "ComponentType" ADD VALUE IF NOT EXISTS 'printer';
ALTER TYPE "ComponentType" ADD VALUE IF NOT EXISTS 'ups';
ALTER TYPE "ComponentType" ADD VALUE IF NOT EXISTS 'avr';
ALTER TYPE "ComponentType" ADD VALUE IF NOT EXISTS 'clicker';
ALTER TYPE "ComponentType" ADD VALUE IF NOT EXISTS 'projector';
ALTER TYPE "ComponentType" ADD VALUE IF NOT EXISTS 'tv';
ALTER TYPE "ComponentType" ADD VALUE IF NOT EXISTS 'signal_booster';
ALTER TYPE "ComponentType" ADD VALUE IF NOT EXISTS 'flash_drive';
ALTER TYPE "ComponentType" ADD VALUE IF NOT EXISTS 'external_hdd';
ALTER TYPE "ComponentType" ADD VALUE IF NOT EXISTS 'hdd_ssd_docking_station';
ALTER TYPE "ComponentType" ADD VALUE IF NOT EXISTS 'nvme_docking_station';

ALTER TABLE "AssetComponent" ADD COLUMN "propertyTag" TEXT;
