-- Generated by: supabase migration new phone_profile
-- Provenance: semantically aligned with oracle-api/prisma/migrations/20260825153000_phone_profile/migration.sql
-- Scope: phone inventory. Company vs BYOD reuses Asset.ownership; serial number,
-- IMEI, and property tag already live on Asset. Only brand/model need a
-- category-specific home.
-- Note: as of this authoring, the "phones.v1" feature rollout is not enabled
-- (no FeatureRollout row, PHONES_ENABLED unset) — this migration is schema-only
-- and safe to apply; the feature stays gated off until that rollout is turned on.
-- Authored only. NOT applied by this agent. Apply via the standard Supabase migration deploy pipeline.

CREATE TABLE "PhoneProfile" (
  "id" TEXT NOT NULL, "assetId" TEXT NOT NULL, "brand" TEXT, "model" TEXT,
  "notes" TEXT, "idempotencyKey" TEXT, "idempotencyPayloadHash" TEXT,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "PhoneProfile_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "PhoneProfile_assetId_key" ON "PhoneProfile"("assetId");
CREATE UNIQUE INDEX "PhoneProfile_idempotencyKey_key" ON "PhoneProfile"("idempotencyKey");
ALTER TABLE "PhoneProfile" ADD CONSTRAINT "PhoneProfile_assetId_fkey" FOREIGN KEY ("assetId") REFERENCES "Asset"("id") ON DELETE CASCADE ON UPDATE CASCADE;
