-- Generated by: supabase migration new access_point_switch_profiles
-- Provenance: semantically aligned with oracle-api/prisma/migrations/20260825150000_access_point_switch_profiles/migration.sql
-- Scope: Access Point / Switch inventory. Metadata only — IP/subnet/gateway/DNS,
-- VLAN membership, physical ports, and credentials all reuse the existing
-- NetworkInterface / IpAddressObservation / InterfaceVlanAssignment /
-- NetworkPort / SecretReference tables via assetId. No new columns for
-- those concerns are added here.
-- Authored only. NOT applied by this agent. Apply via the standard Supabase migration deploy pipeline.

CREATE TYPE "SwitchType" AS ENUM ('managed','unmanaged');

CREATE TABLE "AccessPointProfile" (
  "id" TEXT NOT NULL, "assetId" TEXT NOT NULL, "physicalLocation" TEXT NOT NULL,
  "notes" TEXT, "idempotencyKey" TEXT, "idempotencyPayloadHash" TEXT,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "AccessPointProfile_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "AccessPointProfile_assetId_key" ON "AccessPointProfile"("assetId");
CREATE UNIQUE INDEX "AccessPointProfile_idempotencyKey_key" ON "AccessPointProfile"("idempotencyKey");
CREATE INDEX "AccessPointProfile_physicalLocation_idx" ON "AccessPointProfile"("physicalLocation");
ALTER TABLE "AccessPointProfile" ADD CONSTRAINT "AccessPointProfile_assetId_fkey" FOREIGN KEY ("assetId") REFERENCES "Asset"("id") ON DELETE CASCADE ON UPDATE CASCADE;

CREATE TABLE "SwitchProfile" (
  "id" TEXT NOT NULL, "assetId" TEXT NOT NULL, "switchType" "SwitchType" NOT NULL DEFAULT 'unmanaged',
  "physicalLocation" TEXT NOT NULL, "portCount" INTEGER,
  "notes" TEXT, "idempotencyKey" TEXT, "idempotencyPayloadHash" TEXT,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL, CONSTRAINT "SwitchProfile_pkey" PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX "SwitchProfile_assetId_key" ON "SwitchProfile"("assetId");
CREATE UNIQUE INDEX "SwitchProfile_idempotencyKey_key" ON "SwitchProfile"("idempotencyKey");
CREATE INDEX "SwitchProfile_physicalLocation_idx" ON "SwitchProfile"("physicalLocation");
ALTER TABLE "SwitchProfile" ADD CONSTRAINT "SwitchProfile_assetId_fkey" FOREIGN KEY ("assetId") REFERENCES "Asset"("id") ON DELETE CASCADE ON UPDATE CASCADE;
