-- Generated by: manual authoring (isolation agent), semantically aligned with
-- oracle-api/prisma/migrations/20260823100000_servers_firewall_isp/migration.sql,
-- .../20260823110000_phase5_secret_idempotency_fix/migration.sql,
-- .../20260823113000_phase5_address_lifecycle_fix/migration.sql,
-- .../20260823140000_phase5_shared_policy_and_address_overlap/migration.sql, and
-- .../20260823143000_phase5_circuit_shared_eligibility/migration.sql.
--
-- Scope: additive Phase 5 server, firewall, and ISP circuit inventory metadata
-- only. Never stores server/firewall/ISP passwords, ruleset exports, VPN
-- configs, or other raw credential material -- SecretReference (Phase 4) is
-- the only pointer to secret material, linked here via
-- IspCircuitSecretReference. FirewallProfile.managementInterfaceId links to
-- NetworkInterface (Phase 3), now present because this migration is applied
-- after both the Phase 3 and Phase 4 migrations.
--
-- AUTHORED ONLY. NOT applied by this agent. Apply via the standard Supabase
-- migration deploy pipeline, after Phase 3 and Phase 4 migrations, and only
-- once SERVERS_FIREWALL_ISP_ENABLED / the servers.firewall.isp.v1 feature
-- rollout has been explicitly approved. Preflight existing rows (there
-- should be none, this is a new additive domain) before applying to a
-- database with pre-existing data.

DO $$ BEGIN CREATE TYPE public."ServerEnvironment" AS ENUM ('production','staging','development','test','other'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE public."Criticality" AS ENUM ('critical','high','medium','low'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE public."VirtualizationRole" AS ENUM ('physical','hypervisor','virtual_machine','container_host','other'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE public."ServerRoleType" AS ENUM ('domain_controller','file_server','application_server','database_server','backup_server','dns_server','dhcp_server','other'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE public."FirewallDeploymentMode" AS ENUM ('routed_gateway','transparent_bridge','host_firewall','virtual_appliance','other'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE public."FirewallHaRole" AS ENUM ('standalone','active','passive','member','unknown'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE public."IspServiceType" AS ENUM ('fiber','dsl','cable','wireless','leased_line','satellite','other'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE public."IspCircuitStatus" AS ENUM ('planned','active','degraded','suspended','terminated'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE public."IspAddressingMode" AS ENUM ('static','dhcp','dynamic','pppoe','cgnat','unknown'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE public."CircuitEquipmentRole" AS ENUM ('ont','modem','router','firewall'); EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE TABLE public."ServerProfile" (
  "id" TEXT NOT NULL, "assetId" TEXT NOT NULL,
  "environment" public."ServerEnvironment" NOT NULL, "criticality" public."Criticality" NOT NULL,
  "virtualizationRole" public."VirtualizationRole" NOT NULL,
  "serviceOwner" TEXT NOT NULL, "supportOwner" TEXT, "purpose" TEXT,
  "idempotencyKey" TEXT, "idempotencyPayloadHash" TEXT,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "ServerProfile_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "ServerProfile_assetId_fkey" FOREIGN KEY ("assetId") REFERENCES public."Asset"("id") ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE UNIQUE INDEX "ServerProfile_assetId_key" ON public."ServerProfile"("assetId");
CREATE UNIQUE INDEX "ServerProfile_idempotencyKey_key" ON public."ServerProfile"("idempotencyKey");

CREATE TABLE public."ServerRoleAssignment" (
  "id" TEXT NOT NULL, "serverId" TEXT NOT NULL, "roleType" public."ServerRoleType" NOT NULL,
  "roleName" TEXT, "domainName" TEXT, "isPrimary" BOOLEAN NOT NULL DEFAULT false,
  "validFrom" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "validTo" TIMESTAMP(3), "notes" TEXT,
  "idempotencyKey" TEXT, "idempotencyPayloadHash" TEXT,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "ServerRoleAssignment_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "ServerRoleAssignment_serverId_fkey" FOREIGN KEY ("serverId") REFERENCES public."ServerProfile"("id") ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE UNIQUE INDEX "ServerRoleAssignment_idempotencyKey_key" ON public."ServerRoleAssignment"("idempotencyKey");
CREATE INDEX "ServerRoleAssignment_serverId_validFrom_idx" ON public."ServerRoleAssignment"("serverId","validFrom");

CREATE TABLE public."FirewallProfile" (
  "id" TEXT NOT NULL, "assetId" TEXT NOT NULL,
  "deploymentMode" public."FirewallDeploymentMode" NOT NULL, "haRole" public."FirewallHaRole" NOT NULL,
  "policyOwner" TEXT NOT NULL, "managementInterfaceId" TEXT, "configurationArtifactRef" TEXT,
  "idempotencyKey" TEXT, "idempotencyPayloadHash" TEXT,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "FirewallProfile_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "FirewallProfile_assetId_fkey" FOREIGN KEY ("assetId") REFERENCES public."Asset"("id") ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT "FirewallProfile_managementInterfaceId_fkey" FOREIGN KEY ("managementInterfaceId") REFERENCES public."NetworkInterface"("id") ON DELETE SET NULL ON UPDATE CASCADE
);
CREATE UNIQUE INDEX "FirewallProfile_assetId_key" ON public."FirewallProfile"("assetId");
CREATE UNIQUE INDEX "FirewallProfile_idempotencyKey_key" ON public."FirewallProfile"("idempotencyKey");

CREATE TABLE public."IspCircuit" (
  "id" TEXT NOT NULL, "branchId" TEXT NOT NULL, "providerName" TEXT NOT NULL, "circuitLabel" TEXT NOT NULL,
  "serviceType" public."IspServiceType" NOT NULL, "status" public."IspCircuitStatus" NOT NULL,
  "demarcLocation" TEXT, "downloadMbps" DECIMAL(65,30) NOT NULL, "uploadMbps" DECIMAL(65,30) NOT NULL,
  "addressingMode" public."IspAddressingMode" NOT NULL,
  "isSharedService" BOOLEAN NOT NULL DEFAULT false, "sharedServiceReason" TEXT,
  "activatedAt" TIMESTAMP(3), "terminatedAt" TIMESTAMP(3), "providerCircuitIdMasked" TEXT,
  "idempotencyKey" TEXT, "idempotencyPayloadHash" TEXT,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "IspCircuit_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "IspCircuit_branchId_fkey" FOREIGN KEY ("branchId") REFERENCES public."Branch"("id") ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE UNIQUE INDEX "IspCircuit_idempotencyKey_key" ON public."IspCircuit"("idempotencyKey");
CREATE INDEX "IspCircuit_branchId_status_idx" ON public."IspCircuit"("branchId","status");

CREATE TABLE public."CircuitEquipmentAssignment" (
  "id" TEXT NOT NULL, "circuitId" TEXT NOT NULL, "assetId" TEXT NOT NULL, "role" public."CircuitEquipmentRole" NOT NULL,
  "validFrom" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "validTo" TIMESTAMP(3),
  "idempotencyKey" TEXT, "idempotencyPayloadHash" TEXT,
  "sharedServiceApproved" BOOLEAN NOT NULL DEFAULT false, "sharedServiceReason" TEXT,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL,
  CONSTRAINT "CircuitEquipmentAssignment_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "CircuitEquipmentAssignment_circuitId_fkey" FOREIGN KEY ("circuitId") REFERENCES public."IspCircuit"("id") ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT "CircuitEquipmentAssignment_assetId_fkey" FOREIGN KEY ("assetId") REFERENCES public."Asset"("id") ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE UNIQUE INDEX "CircuitEquipmentAssignment_idempotencyKey_key" ON public."CircuitEquipmentAssignment"("idempotencyKey");
CREATE INDEX "CircuitEquipmentAssignment_circuitId_validFrom_idx" ON public."CircuitEquipmentAssignment"("circuitId","validFrom");

CREATE TABLE public."IspCircuitAddress" (
  "id" TEXT NOT NULL, "circuitId" TEXT NOT NULL, "address" TEXT NOT NULL, "prefixLength" INTEGER NOT NULL,
  "gateway" TEXT, "validFrom" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "validTo" TIMESTAMP(3),
  "idempotencyKey" TEXT, "idempotencyPayloadHash" TEXT,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "IspCircuitAddress_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "IspCircuitAddress_circuitId_fkey" FOREIGN KEY ("circuitId") REFERENCES public."IspCircuit"("id") ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE UNIQUE INDEX "IspCircuitAddress_idempotencyKey_key" ON public."IspCircuitAddress"("idempotencyKey");
CREATE INDEX "IspCircuitAddress_circuitId_validFrom_idx" ON public."IspCircuitAddress"("circuitId","validFrom");

CREATE TABLE public."IspCircuitSecretReference" (
  "id" TEXT NOT NULL, "circuitId" TEXT NOT NULL, "secretReferenceId" TEXT NOT NULL, "purpose" TEXT,
  "idempotencyKey" TEXT, "idempotencyPayloadHash" TEXT,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "IspCircuitSecretReference_pkey" PRIMARY KEY ("id"),
  CONSTRAINT "IspCircuitSecretReference_circuitId_fkey" FOREIGN KEY ("circuitId") REFERENCES public."IspCircuit"("id") ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT "IspCircuitSecretReference_secretReferenceId_fkey" FOREIGN KEY ("secretReferenceId") REFERENCES public."SecretReference"("id") ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE UNIQUE INDEX "IspCircuitSecretReference_circuitId_secretReferenceId_key" ON public."IspCircuitSecretReference"("circuitId","secretReferenceId");
CREATE UNIQUE INDEX "IspCircuitSecretReference_idempotencyKey_key" ON public."IspCircuitSecretReference"("idempotencyKey");

-- Forward-only hardening notes (matches the corresponding local Prisma migrations):
-- PostgreSQL exclusion constraints for circuit-address / server-role temporal overlap are
-- intentionally not applied here because existing deployments may not have btree_gist
-- installed. The API enforces non-overlap via serializable transactions and overlap
-- predicates. Operators may add exclusion constraints after reviewing existing rows, e.g.:
--   CREATE EXTENSION IF NOT EXISTS btree_gist;
--   ALTER TABLE public."IspCircuitAddress" ADD CONSTRAINT "IspCircuitAddress_no_overlap"
--   EXCLUDE USING gist ("circuitId" WITH =, tstzrange("validFrom", COALESCE("validTo", 'infinity'::timestamp), '[)') WITH &&);

-- Row-level security: metadata-only tables, no anon/authenticated access.
-- Application access goes through the API's Prisma service role only.
ALTER TABLE public."ServerProfile" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."ServerRoleAssignment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."FirewallProfile" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."IspCircuit" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."CircuitEquipmentAssignment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."IspCircuitAddress" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."IspCircuitSecretReference" ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public."ServerProfile", public."ServerRoleAssignment", public."FirewallProfile",
  public."IspCircuit", public."CircuitEquipmentAssignment", public."IspCircuitAddress",
  public."IspCircuitSecretReference" FROM anon, authenticated;
REVOKE ALL ON TABLE public."ServerProfile", public."ServerRoleAssignment", public."FirewallProfile",
  public."IspCircuit", public."CircuitEquipmentAssignment", public."IspCircuitAddress",
  public."IspCircuitSecretReference" FROM PUBLIC;
