-- Generated by: supabase migration new asset_attachments
-- Provenance: semantically aligned with oracle-api/prisma/migrations/20260827180000_asset_attachments/migration.sql
-- Scope: attachments uploaded during asset intake/edit (invoices, warranty docs,
-- photos not covered by the intake photo grid). File bytes are stored inline
-- (BYTEA), capped at 5MB by the API layer.
-- Authored only. NOT applied by this agent. Apply via the standard Supabase migration deploy pipeline.

CREATE TABLE "AssetAttachment" (
    "id"           TEXT NOT NULL,
    "assetId"      TEXT NOT NULL,
    "fileName"     TEXT NOT NULL,
    "mimeType"     TEXT NOT NULL,
    "fileSize"     INTEGER NOT NULL,
    "data"         BYTEA NOT NULL,
    "uploadedById" TEXT NOT NULL,
    "createdAt"    TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "AssetAttachment_pkey" PRIMARY KEY ("id")
);

CREATE INDEX "AssetAttachment_assetId_idx" ON "AssetAttachment"("assetId");

ALTER TABLE "AssetAttachment" ADD CONSTRAINT "AssetAttachment_assetId_fkey" FOREIGN KEY ("assetId") REFERENCES "Asset"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "AssetAttachment" ADD CONSTRAINT "AssetAttachment_uploadedById_fkey" FOREIGN KEY ("uploadedById") REFERENCES "SystemUser"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- File bytes may include sensitive documents (invoices, IDs) — deny direct
-- client-role access on Supabase-hosted Postgres, consistent with the other
-- secret-adjacent tables in this schema.
ALTER TABLE "AssetAttachment" ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON TABLE "AssetAttachment" FROM anon, authenticated;
