-- Generated by: supabase migration new phase5_circuit_shared_eligibility
-- Provenance: semantically aligned with oracle-api/prisma/migrations/20260823143000_phase5_circuit_shared_eligibility/migration.sql
-- Scope: explicit shared/global circuit eligibility. Default false is fail-closed.
-- Authored only. NOT applied by this agent. Apply via the standard Supabase migration deploy pipeline.

ALTER TABLE "IspCircuit" ADD COLUMN "isSharedService" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "IspCircuit" ADD COLUMN "sharedServiceReason" TEXT;
