-- Generated by: supabase migration new phase5_address_lifecycle_fix
-- Provenance: semantically aligned with oracle-api/prisma/migrations/20260823113000_phase5_address_lifecycle_fix/migration.sql
-- Scope: adds updatedAt tracking to circuit address lifecycle rows.
-- Authored only. NOT applied by this agent. Apply via the standard Supabase migration deploy pipeline.

ALTER TABLE "IspCircuitAddress" ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
