import { Router, Response } from "express";
import net from "net";
import { prisma } from "../lib/prisma";
import { requireAuth, requirePermission, AuthRequest } from "../middleware/auth";
import { Prisma } from "../generated/prisma/client";

const router = Router();
const writeKeys = new Set(["assetId", "interfaceName", "macAddress", "description"]);
const ipKeys = new Set(["address", "prefixLength", "addressingMode", "gateway", "dnsServers", "source", "observedAt", "validFrom", "validTo"]);
const vlanKeys = new Set(["branchId", "vlanNumber", "vlanName", "cidr", "gateway"]);
const portKeys = new Set(["assetId", "portNumber", "portLabel", "medium", "speedMbps", "poeCapability", "adminStatus", "operationalStatus"]);
const connectionKeys = new Set(["fromPortId", "toPortId", "toInterfaceId", "branchId", "linkType", "effectiveFrom", "effectiveTo"]);
const failUnknown = (body: Record<string, unknown>, allowed: Set<string>, res: Response) => { const fields = Object.keys(body).filter((key) => !allowed.has(key)); if (fields.length) { res.status(400).json({ error: "Unknown network fields.", code: "UNKNOWN_FIELDS", fieldErrors: fields }); return true; } return false; };
export function normalizeMac(value: unknown): string | null { if (value === undefined || value === null || value === "") return null; if (typeof value !== "string" || !/^([0-9a-f]{2}[:-]){5}[0-9a-f]{2}$/i.test(value)) return null; return value.replace(/-/g, ":").toUpperCase(); }
function validDate(value: unknown): Date | null { if (value === undefined || value === null || value === "") return null; if (typeof value !== "string") return null; const date = new Date(value); return Number.isNaN(date.getTime()) ? null : date; }
async function enabled(branchId?: string) { const feature = await prisma.featureRollout.findUnique({ where: { key: "network.v1" } }).catch(() => null); const override = feature && branchId ? await prisma.featureRolloutBranch.findUnique({ where: { featureKey_branchId: { featureKey: feature.key, branchId } } }).catch(() => null) : null; return process.env.NETWORK_INFRA_ENABLED === "true" && Boolean(override?.enabled ?? (feature?.enabledGlobally && feature.status === "enabled")); }
async function scopeAsset(req: AuthRequest, assetId: string) { const [asset, user] = await Promise.all([prisma.asset.findUnique({ where: { id: assetId }, select: { id: true, branchId: true } }), prisma.systemUser.findUnique({ where: { id: req.user!.id }, select: { branchId: true, role: { select: { name: true } } } })]); const superAdmin = user?.role?.name?.toLowerCase() === "super_admin"; return { asset, allowed: Boolean(asset && (superAdmin || user?.branchId === asset.branchId)) }; }
export function validIp(address: unknown, prefix: unknown) { if (typeof address !== "string" || !net.isIP(address)) return false; return Number.isInteger(prefix) && Number(prefix) >= 0 && Number(prefix) <= (net.isIPv4(address) ? 32 : 128); }

router.get("/interfaces", requireAuth, requirePermission("view_inventory"), async (req: AuthRequest, res) => {
  const user = await prisma.systemUser.findUnique({ where: { id: req.user!.id }, select: { branchId: true, role: { select: { name: true } } } }); const superAdmin = user?.role?.name?.toLowerCase() === "super_admin";
  if (!superAdmin && !user?.branchId) { res.json({ items: [], page: 1, pageSize: 20, total: 0 }); return; }
  const assetId = typeof req.query.assetId === "string" ? req.query.assetId : undefined; const page = Math.max(1, Number(req.query.page) || 1); const pageSize = Math.min(100, Math.max(1, Number(req.query.pageSize) || 20));
  const where = { ...(assetId ? { assetId } : {}), ...(!superAdmin ? { asset: { branchId: user!.branchId! } } : {}) };
  const [items, total] = await Promise.all([prisma.networkInterface.findMany({ where, skip: (page - 1) * pageSize, take: pageSize, orderBy: { updatedAt: "desc" } }), prisma.networkInterface.count({ where })]); res.json({ items, page, pageSize, total });
});

router.post("/interfaces", requireAuth, requirePermission("manage_infrastructure_assets"), async (req: AuthRequest, res) => {
  if (!(await enabled())) { res.status(503).json({ error: "Network infrastructure is disabled.", code: "NETWORK_DISABLED" }); return; }
  const body = req.body as Record<string, unknown>; if (failUnknown(body, writeKeys, res)) return; const assetId = typeof body.assetId === "string" ? body.assetId : ""; const interfaceName = typeof body.interfaceName === "string" ? body.interfaceName.trim() : ""; const macAddress = normalizeMac(body.macAddress); if (!assetId || !interfaceName || (body.macAddress !== undefined && body.macAddress !== null && !macAddress)) { res.status(400).json({ error: "assetId and interfaceName are required; macAddress must be valid.", code: "VALIDATION_ERROR" }); return; }
  const scope = await scopeAsset(req, assetId); if (!scope.asset) { res.status(404).json({ error: "Asset not found." }); return; } if (!scope.allowed) { res.status(403).json({ error: "Asset is outside your branch scope." }); return; }
  const idempotencyKey = typeof req.headers["idempotency-key"] === "string" ? req.headers["idempotency-key"].trim() : ""; if (!idempotencyKey) { res.status(400).json({ error: "Idempotency-Key is required." }); return; }
  try { const prior = await prisma.networkInterface.findUnique({ where: { idempotencyKey } }); if (prior) { res.json(prior); return; } const item = await prisma.networkInterface.create({ data: { assetId, interfaceName, macAddress, description: typeof body.description === "string" ? body.description.trim() : null, idempotencyKey } }); res.status(201).json(item); } catch { res.status(409).json({ error: "Interface already exists or conflicts.", code: "DUPLICATE_INTERFACE" }); }
});

router.put("/interfaces/:id", requireAuth, requirePermission("manage_infrastructure_assets"), async (req: AuthRequest, res) => {
  if (!(await enabled())) { res.status(503).json({ error: "Network infrastructure is disabled.", code: "NETWORK_DISABLED" }); return; }
  const body = req.body as Record<string, unknown>; if (failUnknown(body, new Set(["interfaceName", "macAddress", "description", "expectedUpdatedAt"]), res)) return; const existing = await prisma.networkInterface.findUnique({ where: { id: req.params.id } }); if (!existing) { res.status(404).json({ error: "Interface not found." }); return; } const scope = await scopeAsset(req, existing.assetId); if (!scope.allowed) { res.status(403).json({ error: "Interface is outside your branch scope." }); return; } const expected = validDate(body.expectedUpdatedAt); if (!expected || expected.getTime() !== existing.updatedAt.getTime()) { res.status(409).json({ error: "Interface changed since it was loaded.", code: "STALE_WRITE" }); return; } const mac = body.macAddress === undefined ? existing.macAddress : normalizeMac(body.macAddress); if (body.macAddress !== undefined && body.macAddress !== null && !mac) { res.status(400).json({ error: "macAddress must be valid." }); return; }
  const updated = await prisma.networkInterface.updateMany({ where: { id: existing.id, updatedAt: expected }, data: { interfaceName: typeof body.interfaceName === "string" ? body.interfaceName.trim() : existing.interfaceName, macAddress: mac, description: typeof body.description === "string" ? body.description.trim() : existing.description } }); if (updated.count !== 1) { res.status(409).json({ error: "Interface changed since it was loaded.", code: "STALE_WRITE" }); return; } res.json(await prisma.networkInterface.findUnique({ where: { id: existing.id } }));
});

router.post("/interfaces/:id/ip-observations", requireAuth, requirePermission("manage_infrastructure_assets"), requirePermission("view_sensitive_network_fields"), async (req: AuthRequest, res) => {
  if (!(await enabled())) { res.status(503).json({ error: "Network infrastructure is disabled.", code: "NETWORK_DISABLED" }); return; }
  const body = req.body as Record<string, unknown>; if (failUnknown(body, ipKeys, res)) return;
  const key = typeof req.headers["idempotency-key"] === "string" ? req.headers["idempotency-key"].trim() : ""; if (!key) { res.status(400).json({ error: "Idempotency-Key is required." }); return; }
  const iface = await prisma.networkInterface.findUnique({ where: { id: req.params.id }, select: { id: true, assetId: true } }); if (!iface) { res.status(404).json({ error: "Interface not found." }); return; } const scope = await scopeAsset(req, iface.assetId); if (!scope.allowed) { res.status(403).json({ error: "Interface is outside your branch scope." }); return; }
  if (!validIp(body.address, body.prefixLength)) { res.status(400).json({ error: "address and prefixLength are invalid.", code: "VALIDATION_ERROR" }); return; } const validFrom = validDate(body.validFrom) ?? new Date(); const validTo = validDate(body.validTo); if (validTo && validTo <= validFrom) { res.status(400).json({ error: "validTo must be later than validFrom.", code: "VALIDATION_ERROR" }); return; } const mode = body.addressingMode; if (!["static", "dhcp", "dynamic", "unknown"].includes(String(mode))) { res.status(400).json({ error: "addressingMode is invalid.", code: "VALIDATION_ERROR" }); return; }
  const prior = await prisma.ipAddressObservation.findUnique({ where: { idempotencyKey: key } }); if (prior) { res.json(prior); return; }
  const item = await prisma.$transaction(async (tx) => { const created = await tx.ipAddressObservation.create({ data: { interfaceId: iface.id, address: body.address as string, prefixLength: body.prefixLength as number, family: net.isIPv4(body.address as string) ? "ipv4" : "ipv6", addressingMode: mode as never, gateway: typeof body.gateway === "string" ? body.gateway : null, dnsServers: Array.isArray(body.dnsServers) && body.dnsServers.every((v) => typeof v === "string") ? body.dnsServers as string[] : [], source: typeof body.source === "string" ? body.source : "manual", observedAt: validDate(body.observedAt) ?? new Date(), validFrom, validTo, idempotencyKey: key } }); await tx.activityLog.create({ data: { userId: req.user!.id, action: "network_ip_observation_created", entity: "IpAddressObservation", entityId: created.id, metadata: { interfaceId: iface.id, address: created.address, source: created.source } } }); return created; }); res.status(201).json(item);
});

router.post("/vlans", requireAuth, requirePermission("manage_infrastructure_assets"), async (req: AuthRequest, res) => { if (!(await enabled())) { res.status(503).json({ error: "Network infrastructure is disabled.", code: "NETWORK_DISABLED" }); return; } const body = req.body as Record<string, unknown>; if (failUnknown(body, vlanKeys, res)) return; const branchId = typeof body.branchId === "string" ? body.branchId : ""; const vlanNumber = Number(body.vlanNumber); if (!branchId || !Number.isInteger(vlanNumber) || vlanNumber < 1 || vlanNumber > 4094) { res.status(400).json({ error: "branchId and vlanNumber 1-4094 are required.", code: "VALIDATION_ERROR" }); return; } const user = await prisma.systemUser.findUnique({ where: { id: req.user!.id }, select: { branchId: true, role: { select: { name: true } } } }); if (user?.role?.name?.toLowerCase() !== "super_admin" && user?.branchId !== branchId) { res.status(403).json({ error: "Branch is outside your scope." }); return; } try { const item = await prisma.vlan.create({ data: { branchId, vlanNumber, vlanName: typeof body.vlanName === "string" ? body.vlanName.trim() : null, cidr: typeof body.cidr === "string" ? body.cidr.trim() : null, gateway: typeof body.gateway === "string" ? body.gateway.trim() : null } }); res.status(201).json(item); } catch { res.status(409).json({ error: "VLAN already exists in this branch.", code: "DUPLICATE_VLAN" }); } });

router.post("/ports", requireAuth, requirePermission("manage_infrastructure_assets"), async (req: AuthRequest, res) => { if (!(await enabled())) { res.status(503).json({ error: "Network infrastructure is disabled.", code: "NETWORK_DISABLED" }); return; } const body = req.body as Record<string, unknown>; if (failUnknown(body, portKeys, res)) return; const assetId = typeof body.assetId === "string" ? body.assetId : ""; const portNumber = typeof body.portNumber === "string" ? body.portNumber.trim() : ""; if (!assetId || !portNumber || (body.speedMbps !== undefined && (!Number.isInteger(body.speedMbps) || Number(body.speedMbps) < 0))) { res.status(400).json({ error: "assetId, portNumber, and valid speedMbps are required.", code: "VALIDATION_ERROR" }); return; } const scope = await scopeAsset(req, assetId); if (!scope.asset) { res.status(404).json({ error: "Asset not found." }); return; } if (!scope.allowed) { res.status(403).json({ error: "Asset is outside your branch scope." }); return; } try { const item = await prisma.networkPort.create({ data: { assetId, portNumber, portLabel: typeof body.portLabel === "string" ? body.portLabel.trim() : null, medium: typeof body.medium === "string" ? body.medium.trim() : null, speedMbps: body.speedMbps as number | undefined, poeCapability: typeof body.poeCapability === "string" ? body.poeCapability.trim() : null, adminStatus: (body.adminStatus as never) ?? "unknown", operationalStatus: (body.operationalStatus as never) ?? "unknown" } }); res.status(201).json(item); } catch { res.status(409).json({ error: "Port already exists on this asset.", code: "DUPLICATE_PORT" }); } });

router.post("/connections", requireAuth, requirePermission("manage_infrastructure_assets"), async (req: AuthRequest, res) => { if (!(await enabled())) { res.status(503).json({ error: "Network infrastructure is disabled.", code: "NETWORK_DISABLED" }); return; } if (!req.headers["idempotency-key"]) { res.status(400).json({ error: "Idempotency-Key is required." }); return; } const body = req.body as Record<string, unknown>; if (failUnknown(body, connectionKeys, res)) return; const fromPortId = typeof body.fromPortId === "string" ? body.fromPortId : ""; const toPortId = typeof body.toPortId === "string" ? body.toPortId : undefined; const toInterfaceId = typeof body.toInterfaceId === "string" ? body.toInterfaceId : undefined; const branchId = typeof body.branchId === "string" ? body.branchId : ""; if (!fromPortId || !branchId || Boolean(toPortId) === Boolean(toInterfaceId) || !["physical", "logical", "wan"].includes(String(body.linkType))) { res.status(400).json({ error: "fromPortId, branchId, linkType, and exactly one target are required.", code: "VALIDATION_ERROR" }); return; } const user = await prisma.systemUser.findUnique({ where: { id: req.user!.id }, select: { branchId: true, role: { select: { name: true } } } }); const superAdmin = user?.role?.name?.toLowerCase() === "super_admin"; if (!superAdmin && user?.branchId !== branchId) { res.status(403).json({ error: "Branch is outside your scope." }); return; } const from = await prisma.networkPort.findUnique({ where: { id: fromPortId }, select: { id: true, asset: { select: { branchId: true } } } }); if (!from || (!superAdmin && from.asset.branchId !== user?.branchId)) { res.status(403).json({ error: "Port is outside your branch scope." }); return; } if (toPortId) { const target = await prisma.networkPort.findUnique({ where: { id: toPortId }, select: { id: true, asset: { select: { branchId: true } } } }); if (!target || (!superAdmin && target.asset.branchId !== user?.branchId)) { res.status(403).json({ error: "Target port is outside your branch scope." }); return; } } const effectiveFrom = validDate(body.effectiveFrom) ?? new Date(); const item = await prisma.$transaction(async (tx) => { await tx.portConnection.updateMany({ where: { fromPortId, effectiveTo: null }, data: { effectiveTo: effectiveFrom } }); return tx.portConnection.create({ data: { fromPortId, toPortId, toInterfaceId, branchId, linkType: body.linkType as never, effectiveFrom, effectiveTo: validDate(body.effectiveTo) } }); }); res.status(201).json(item); });

router.get("/interfaces/:id/ip-observations", requireAuth, requirePermission("view_inventory"), requirePermission("view_sensitive_network_fields"), async (req: AuthRequest, res) => {
  const iface = await prisma.networkInterface.findUnique({ where: { id: req.params.id }, select: { id: true, assetId: true } }); if (!iface) { res.status(404).json({ error: "Interface not found." }); return; } const scope = await scopeAsset(req, iface.assetId); if (!scope.allowed) { res.status(403).json({ error: "Interface is outside your branch scope." }); return; } res.json({ items: await prisma.ipAddressObservation.findMany({ where: { interfaceId: iface.id }, orderBy: { observedAt: "desc" } }) });
});
router.get("/vlans", requireAuth, requirePermission("view_inventory"), requirePermission("view_sensitive_network_fields"), async (req: AuthRequest, res) => {
  const branchId = typeof req.query.branchId === "string" ? req.query.branchId : undefined; const user = await prisma.systemUser.findUnique({ where: { id: req.user!.id }, select: { branchId: true, role: { select: { name: true } } } }); const superAdmin = user?.role?.name?.toLowerCase() === "super_admin"; if (!superAdmin && (!user?.branchId || (branchId && branchId !== user.branchId))) { res.status(403).json({ error: "Branch is outside your scope." }); return; } res.json({ items: await prisma.vlan.findMany({ where: { branchId: superAdmin ? branchId : user!.branchId! }, orderBy: { vlanNumber: "asc" } }) });
});
router.get("/topology", requireAuth, requirePermission("view_inventory"), requirePermission("view_sensitive_network_fields"), async (req: AuthRequest, res) => {
  const branchId = typeof req.query.branchId === "string" ? req.query.branchId : undefined; const user = await prisma.systemUser.findUnique({ where: { id: req.user!.id }, select: { branchId: true, role: { select: { name: true } } } }); const superAdmin = user?.role?.name?.toLowerCase() === "super_admin"; if (!superAdmin && (!user?.branchId || (branchId && branchId !== user.branchId))) { res.status(403).json({ error: "Branch is outside your scope." }); return; } const where = { ...(superAdmin && branchId ? { branchId } : (!superAdmin ? { branchId: user!.branchId! } : {})) }; res.json({ items: await prisma.portConnection.findMany({ where, include: { fromPort: true, toPort: true, toInterface: true }, orderBy: { effectiveFrom: "desc" } }) });
});
router.get("/branches/:branchId/connectivity", requireAuth, requirePermission("view_inventory"), requirePermission("view_sensitive_network_fields"), async (req: AuthRequest, res) => {
  const user = await prisma.systemUser.findUnique({ where: { id: req.user!.id }, select: { branchId: true, role: { select: { name: true } } } }); if (user?.role?.name?.toLowerCase() !== "super_admin" && user?.branchId !== req.params.branchId) { res.status(403).json({ error: "Branch is outside your scope." }); return; } const [interfaces, ports, vlans, connections] = await Promise.all([prisma.networkInterface.count({ where: { asset: { branchId: req.params.branchId } } }), prisma.networkPort.count({ where: { asset: { branchId: req.params.branchId } } }), prisma.vlan.count({ where: { branchId: req.params.branchId } }), prisma.portConnection.count({ where: { branchId: req.params.branchId, effectiveTo: null } })]); res.json({ branchId: req.params.branchId, interfaces, ports, vlans, activeConnections: connections });
});
router.post("/vlan-assignments", requireAuth, requirePermission("manage_infrastructure_assets"), requirePermission("view_sensitive_network_fields"), async (req: AuthRequest, res) => {
  if (!(await enabled())) { res.status(503).json({ error: "Network infrastructure is disabled.", code: "NETWORK_DISABLED" }); return; }
  const body = req.body as Record<string, unknown>; const allowed = new Set(["interfaceId", "vlanId", "taggingMode", "isNative", "effectiveFrom", "effectiveTo"]); if (failUnknown(body, allowed, res)) return;
  const interfaceId = typeof body.interfaceId === "string" ? body.interfaceId : ""; const vlanId = typeof body.vlanId === "string" ? body.vlanId : ""; const mode = String(body.taggingMode); const effectiveFrom = validDate(body.effectiveFrom) ?? new Date(); const effectiveTo = validDate(body.effectiveTo); if (!interfaceId || !vlanId || !["access", "tagged", "trunk"].includes(mode) || (effectiveTo && effectiveTo <= effectiveFrom)) { res.status(400).json({ error: "interfaceId, vlanId, taggingMode, and valid effective dates are required.", code: "VALIDATION_ERROR" }); return; }
  const [iface, vlan] = await Promise.all([prisma.networkInterface.findUnique({ where: { id: interfaceId }, select: { id: true, asset: { select: { branchId: true } } } }), prisma.vlan.findUnique({ where: { id: vlanId }, select: { id: true, branchId: true } })]); if (!iface || !vlan) { res.status(404).json({ error: "Interface or VLAN not found." }); return; } if (!iface.asset.branchId || iface.asset.branchId !== vlan.branchId) { res.status(400).json({ error: "Interface and VLAN must belong to the same branch." }); return; } const scope = await scopeAsset(req, (await prisma.networkInterface.findUnique({ where: { id: interfaceId }, select: { assetId: true } }))!.assetId); if (!scope.allowed) { res.status(403).json({ error: "Interface is outside your branch scope." }); return; }
  const idempotencyKey = typeof req.headers["idempotency-key"] === "string" ? req.headers["idempotency-key"].trim() : ""; if (!idempotencyKey) { res.status(400).json({ error: "Idempotency-Key is required." }); return; } const prior = await prisma.interfaceVlanAssignment.findUnique({ where: { idempotencyKey } }); if (prior) { res.json(prior); return; }
  const item = await prisma.$transaction(async (tx) => { await tx.interfaceVlanAssignment.updateMany({ where: { interfaceId, effectiveTo: null }, data: { effectiveTo: effectiveFrom } }); const created = await tx.interfaceVlanAssignment.create({ data: { interfaceId, vlanId, taggingMode: mode as never, isNative: body.isNative === true, effectiveFrom, effectiveTo, idempotencyKey } }); await tx.activityLog.create({ data: { userId: req.user!.id, action: "network_vlan_assignment_created", entity: "InterfaceVlanAssignment", entityId: created.id, metadata: { interfaceId, vlanId, taggingMode: mode } } }); return created; }); res.status(201).json(item);
});
export default router;
