import { Router } from "express";
import crypto from "crypto";
import { prisma } from "../lib/prisma";
import { requireAuth, requirePermission, AuthRequest } from "../middleware/auth";
import { encryptDeviceCredentials, deviceCredentialKeyConfigured, type DeviceCredentialPayload } from "../lib/deviceCredentialCrypto";
import { broadcastChange } from "../lib/ws";

const router = Router();
const featureEnabled = async (branchId?: string) => { const f = await prisma.featureRollout.findUnique({ where: { key: "network.v1" } }).catch(() => null); const override = f && branchId ? await prisma.featureRolloutBranch.findUnique({ where: { featureKey_branchId: { featureKey: f.key, branchId } } }).catch(() => null) : null; return process.env.NETWORK_INFRA_ENABLED === "true" && Boolean(override?.enabled ?? (f?.enabledGlobally && f.status === "enabled")); };
const keyOf = (req: AuthRequest) => typeof req.headers["idempotency-key"] === "string" ? req.headers["idempotency-key"].trim() : "";
const branchUser = async (req: AuthRequest) => prisma.systemUser.findUnique({ where: { id: req.user!.id }, select: { branchId: true, role: { select: { name: true } } } });
const superUser = (u: { role: { name: string } | null } | null) => u?.role?.name.toLowerCase() === "super_admin";
const payloadHash = (value: unknown) => crypto.createHash("sha256").update(JSON.stringify(value)).digest("hex");

router.use("/connections", async (req, res, next) => { if (req.method !== "POST") { next(); return; } const branchId = typeof req.body?.branchId === "string" ? req.body.branchId : undefined; if (!(await featureEnabled(branchId))) { res.status(503).json({ error: "Network infrastructure is disabled.", code: "NETWORK_DISABLED" }); return; } next(); });
router.use("/interfaces/:id", async (req, res, next) => { if (req.method !== "PUT") { next(); return; } const iface = await prisma.networkInterface.findUnique({ where: { id: req.params.id }, select: { asset: { select: { branchId: true } } } }); if (!(await featureEnabled(iface?.asset.branchId ?? undefined))) { res.status(503).json({ error: "Network infrastructure is disabled.", code: "NETWORK_DISABLED" }); return; } next(); });
router.use("/vlan-assignments", async (req, res, next) => { if (req.method !== "POST") { next(); return; } const ifaceId = typeof req.body?.interfaceId === "string" ? req.body.interfaceId : undefined; const iface = ifaceId ? await prisma.networkInterface.findUnique({ where: { id: ifaceId }, select: { asset: { select: { branchId: true } } } }) : null; if (!(await featureEnabled(iface?.asset.branchId ?? undefined))) { res.status(503).json({ error: "Network infrastructure is disabled.", code: "NETWORK_DISABLED" }); return; } next(); });

router.post("/vlan-assignments", requireAuth, requirePermission("manage_infrastructure_assets"), requirePermission("view_sensitive_network_fields"), async (req: AuthRequest, res) => {
  const b = req.body as Record<string, unknown>; const key = keyOf(req); const ifaceId = typeof b.interfaceId === "string" ? b.interfaceId : ""; const vlanId = typeof b.vlanId === "string" ? b.vlanId : ""; if (!key || !ifaceId || !vlanId) { res.status(400).json({ error: "interfaceId, vlanId, and Idempotency-Key are required." }); return; } const hash = payloadHash(b); const prior = await prisma.interfaceVlanAssignment.findUnique({ where: { idempotencyKey: key } }); if (prior) { if (prior.idempotencyPayloadHash !== hash) { res.status(409).json({ error: "Idempotency-Key was reused for different data.", code: "IDEMPOTENCY_KEY_REUSED" }); return; } res.json(prior); return; } const effectiveFrom = typeof b.effectiveFrom === "string" ? new Date(b.effectiveFrom) : new Date(); const iface = await prisma.networkInterface.findUnique({ where: { id: ifaceId }, select: { asset: { select: { branchId: true } } } }); const vlan = await prisma.vlan.findUnique({ where: { id: vlanId }, select: { branchId: true } }); if (!iface || !vlan || iface.asset.branchId !== vlan.branchId) { res.status(400).json({ error: "Interface and VLAN must share a branch." }); return; } const item = await prisma.$transaction(async (tx) => { const created = await tx.interfaceVlanAssignment.create({ data: { interfaceId: ifaceId, vlanId, taggingMode: (b.taggingMode as never) ?? "access", isNative: b.isNative === true, effectiveFrom, effectiveTo: typeof b.effectiveTo === "string" ? new Date(b.effectiveTo) : null, idempotencyKey: key, idempotencyPayloadHash: hash } }); await tx.activityLog.create({ data: { userId: req.user!.id, action: "network_vlan_assignment_created", entity: "InterfaceVlanAssignment", entityId: created.id, metadata: { interfaceId: ifaceId, vlanId } } }); return created; }); broadcastChange({ entity: "InterfaceVlanAssignment", action: "network_vlan_assignment_created", entityId: item.id, branchId: iface.asset.branchId }); res.status(201).json(item);
});

router.post("/interfaces", requireAuth, requirePermission("manage_infrastructure_assets"), async (req: AuthRequest, res) => {
  const b = req.body as Record<string, unknown>; const assetId = typeof b.assetId === "string" ? b.assetId : ""; const key = keyOf(req); const asset = await prisma.asset.findUnique({ where: { id: assetId }, select: { branchId: true } }); const user = await branchUser(req); if (!asset) { res.status(404).json({ error: "Asset not found." }); return; } if (!superUser(user) && user?.branchId !== asset.branchId) { res.status(403).json({ error: "Asset is outside your scope." }); return; } if (!(await featureEnabled(asset.branchId ?? undefined))) { res.status(503).json({ error: "Network infrastructure is disabled.", code: "NETWORK_DISABLED" }); return; } if (!key || typeof b.interfaceName !== "string" || !b.interfaceName.trim()) { res.status(400).json({ error: "interfaceName and Idempotency-Key are required." }); return; } const hash = payloadHash({ assetId, interfaceName: b.interfaceName.trim(), macAddress: b.macAddress ?? null, description: b.description ?? null }); const prior = await prisma.networkInterface.findUnique({ where: { idempotencyKey: key } }); if (prior) { if (prior.idempotencyPayloadHash !== hash) { res.status(409).json({ error: "Idempotency-Key was reused for different data.", code: "IDEMPOTENCY_KEY_REUSED" }); return; } res.json(prior); return; } const created = await prisma.$transaction(async (tx) => { const item = await tx.networkInterface.create({ data: { assetId, interfaceName: b.interfaceName as string, macAddress: typeof b.macAddress === "string" ? b.macAddress : null, description: typeof b.description === "string" ? b.description : null, idempotencyKey: key, idempotencyPayloadHash: hash } }); await tx.activityLog.create({ data: { userId: req.user!.id, action: "network_interface_created", entity: "NetworkInterface", entityId: item.id, metadata: { assetId, interfaceName: item.interfaceName, macAddress: item.macAddress ? `${item.macAddress.slice(0, 5)}***` : null } } }); return item; }); broadcastChange({ entity: "NetworkInterface", action: "network_interface_created", entityId: created.id, branchId: asset.branchId }); res.status(201).json(created);
});

router.post("/interfaces/:id/ip-observations", requireAuth, requirePermission("manage_infrastructure_assets"), requirePermission("view_sensitive_network_fields"), async (req: AuthRequest, res) => {
  const b = req.body as Record<string, unknown>; const key = keyOf(req); const iface = await prisma.networkInterface.findUnique({ where: { id: req.params.id }, select: { id: true, assetId: true, asset: { select: { branchId: true } } } }); if (!iface) { res.status(404).json({ error: "Interface not found." }); return; } const user = await branchUser(req); if (!superUser(user) && user?.branchId !== iface.asset.branchId) { res.status(403).json({ error: "Interface is outside your scope." }); return; } if (!(await featureEnabled(iface.asset.branchId ?? undefined))) { res.status(503).json({ error: "Network infrastructure is disabled.", code: "NETWORK_DISABLED" }); return; } if (!key || typeof b.address !== "string" || !Number.isInteger(b.prefixLength)) { res.status(400).json({ error: "address, prefixLength, and Idempotency-Key are required." }); return; } const hash = payloadHash(b); const prior = await prisma.ipAddressObservation.findUnique({ where: { idempotencyKey: key } }); if (prior) { if (prior.idempotencyPayloadHash !== hash) { res.status(409).json({ error: "Idempotency-Key was reused for different data.", code: "IDEMPOTENCY_KEY_REUSED" }); return; } res.json(prior); return; } const addressMask = `${b.address.split(".").slice(0, 3).join(".")}.***`; const created = await prisma.$transaction(async (tx) => { const item = await tx.ipAddressObservation.create({ data: { interfaceId: iface.id, address: b.address as string, prefixLength: b.prefixLength as number, family: String(b.address).includes(":") ? "ipv6" : "ipv4", addressingMode: (b.addressingMode as never) ?? "unknown", gateway: typeof b.gateway === "string" ? b.gateway : null, dnsServers: Array.isArray(b.dnsServers) ? b.dnsServers as string[] : [], source: typeof b.source === "string" ? b.source : "manual", observedAt: new Date(), validFrom: new Date(), idempotencyKey: key, idempotencyPayloadHash: hash } }); await tx.activityLog.create({ data: { userId: req.user!.id, action: "network_ip_observation_created", entity: "IpAddressObservation", entityId: item.id, metadata: { interfaceId: iface.id, address: addressMask, source: item.source } } }); return item; }); broadcastChange({ entity: "IpAddressObservation", action: "network_ip_observation_created", entityId: created.id, branchId: iface.asset.branchId }); res.status(201).json(created);
});

router.put("/interfaces/:id", requireAuth, requirePermission("manage_infrastructure_assets"), async (req: AuthRequest, res) => {
  const unknown = Object.keys(req.body as Record<string, unknown>).filter((k) => !["interfaceName", "macAddress", "description", "expectedUpdatedAt"].includes(k)); if (unknown.length) { res.status(400).json({ error: "Unknown network fields.", fieldErrors: unknown }); return; }
  const existing = await prisma.networkInterface.findUnique({ where: { id: req.params.id } }); if (!existing) { res.status(404).json({ error: "Interface not found." }); return; } const user = await branchUser(req); const asset = await prisma.asset.findUnique({ where: { id: existing.assetId }, select: { branchId: true } }); if (!superUser(user) && user?.branchId !== asset?.branchId) { res.status(403).json({ error: "Interface is outside your scope." }); return; } const expected = typeof req.body.expectedUpdatedAt === "string" ? new Date(req.body.expectedUpdatedAt) : null; if (!expected || expected.getTime() !== existing.updatedAt.getTime()) { res.status(409).json({ error: "Interface changed since it was loaded.", code: "STALE_WRITE" }); return; } const result = await prisma.$transaction(async (tx) => { const updated = await tx.networkInterface.updateMany({ where: { id: existing.id, updatedAt: expected }, data: { interfaceName: typeof req.body.interfaceName === "string" ? req.body.interfaceName.trim() : existing.interfaceName, description: typeof req.body.description === "string" ? req.body.description.trim() : existing.description } }); if (updated.count !== 1) throw new Error("STALE_WRITE"); const item = await tx.networkInterface.findUnique({ where: { id: existing.id } }); await tx.activityLog.create({ data: { userId: req.user!.id, action: "network_interface_updated", entity: "NetworkInterface", entityId: existing.id, metadata: { interfaceId: existing.id, changedFields: Object.keys(req.body).filter((k) => k !== "expectedUpdatedAt") } } }); return item; }); broadcastChange({ entity: "NetworkInterface", action: "network_interface_updated", entityId: existing.id, branchId: asset?.branchId ?? null }); res.json(result);
});

router.post("/vlans", requireAuth, requirePermission("manage_infrastructure_assets"), requirePermission("view_sensitive_network_fields"), async (req: AuthRequest, res) => {
  const b = req.body as Record<string, unknown>; const key = keyOf(req); const allowed = ["branchId", "vlanNumber", "vlanName", "cidr", "gateway"]; const unknown = Object.keys(b).filter((k) => !allowed.includes(k)); if (unknown.length || !key) { res.status(400).json({ error: unknown.length ? "Unknown network fields." : "Idempotency-Key is required.", fieldErrors: unknown }); return; }
  const branchId = typeof b.branchId === "string" ? b.branchId : ""; const vlanNumber = Number(b.vlanNumber); const user = await branchUser(req); if (!branchId || !Number.isInteger(vlanNumber) || vlanNumber < 1 || vlanNumber > 4094) { res.status(400).json({ error: "vlanNumber must be 1-4094.", code: "VALIDATION_ERROR" }); return; } if (!superUser(user) && user?.branchId !== branchId) { res.status(403).json({ error: "Branch is outside your scope." }); return; } if (!(await featureEnabled(branchId))) { res.status(503).json({ error: "Network infrastructure is disabled.", code: "NETWORK_DISABLED" }); return; }
  const name = typeof b.vlanName === "string" ? b.vlanName.trim() : null; const cidr = typeof b.cidr === "string" ? b.cidr.trim() : null; const gateway = typeof b.gateway === "string" ? b.gateway.trim() : null; const hash = payloadHash({ branchId, vlanNumber, vlanName: name, cidr, gateway }); const prior = await prisma.vlan.findUnique({ where: { idempotencyKey: key } }); if (prior) { if (prior.idempotencyPayloadHash !== hash) { res.status(409).json({ error: "Idempotency-Key was reused for different data.", code: "IDEMPOTENCY_KEY_REUSED" }); return; } res.json(prior); return; }
  try { const result = await prisma.$transaction(async (tx) => { const created = await tx.vlan.create({ data: { branchId, vlanNumber, vlanName: name, cidr, gateway, idempotencyKey: key, idempotencyPayloadHash: hash } }); await tx.activityLog.create({ data: { userId: req.user!.id, action: "network_vlan_created", entity: "Vlan", entityId: created.id, metadata: { branchId, vlanNumber } } }); return created; }); broadcastChange({ entity: "Vlan", action: "network_vlan_created", entityId: result.id, branchId }); res.status(201).json(result); } catch { res.status(409).json({ error: "VLAN already exists in this branch.", code: "DUPLICATE_VLAN" }); }
});

router.post("/ports", requireAuth, requirePermission("manage_infrastructure_assets"), async (req: AuthRequest, res) => {
  const b = req.body as Record<string, unknown>; const key = keyOf(req); const unknown = Object.keys(b).filter((k) => !["assetId", "portNumber", "portLabel", "medium", "speedMbps", "poeCapability", "adminStatus", "operationalStatus"].includes(k)); if (unknown.length || !key) { res.status(400).json({ error: unknown.length ? "Unknown network fields." : "Idempotency-Key is required.", fieldErrors: unknown }); return; }
  const assetId = typeof b.assetId === "string" ? b.assetId : ""; const portNumber = typeof b.portNumber === "string" ? b.portNumber.trim() : ""; const asset = await prisma.asset.findUnique({ where: { id: assetId }, select: { branchId: true } }); const user = await branchUser(req); if (!asset) { res.status(404).json({ error: "Asset not found." }); return; } if (!superUser(user) && user?.branchId !== asset.branchId) { res.status(403).json({ error: "Asset is outside your scope." }); return; } if (!(await featureEnabled(asset.branchId ?? undefined))) { res.status(503).json({ error: "Network infrastructure is disabled.", code: "NETWORK_DISABLED" }); return; } if (!portNumber || (b.speedMbps !== undefined && (!Number.isInteger(b.speedMbps) || Number(b.speedMbps) < 0))) { res.status(400).json({ error: "portNumber and valid speedMbps are required.", code: "VALIDATION_ERROR" }); return; }
  const hash = payloadHash(b); const prior = await prisma.networkPort.findUnique({ where: { idempotencyKey: key } }); if (prior) { if (prior.idempotencyPayloadHash !== hash) { res.status(409).json({ error: "Idempotency-Key was reused for different data.", code: "IDEMPOTENCY_KEY_REUSED" }); return; } res.json(prior); return; }
  try { const result = await prisma.$transaction(async (tx) => { const created = await tx.networkPort.create({ data: { assetId, portNumber, portLabel: typeof b.portLabel === "string" ? b.portLabel.trim() : null, medium: typeof b.medium === "string" ? b.medium.trim() : null, speedMbps: b.speedMbps as number | undefined, poeCapability: typeof b.poeCapability === "string" ? b.poeCapability.trim() : null, adminStatus: (b.adminStatus as never) ?? "unknown", operationalStatus: (b.operationalStatus as never) ?? "unknown", idempotencyKey: key, idempotencyPayloadHash: hash } }); await tx.activityLog.create({ data: { userId: req.user!.id, action: "network_port_created", entity: "NetworkPort", entityId: created.id, metadata: { assetId, portNumber } } }); return created; }); broadcastChange({ entity: "NetworkPort", action: "network_port_created", entityId: result.id, branchId: asset.branchId }); res.status(201).json(result); } catch { res.status(409).json({ error: "Port already exists on this asset.", code: "DUPLICATE_PORT" }); }
});

router.post("/connections", requireAuth, requirePermission("manage_infrastructure_assets"), requirePermission("view_sensitive_network_fields"), async (req: AuthRequest, res) => {
  const b = req.body as Record<string, unknown>; const key = keyOf(req); const unknown = Object.keys(b).filter((k) => !["fromPortId", "toPortId", "toInterfaceId", "branchId", "linkType", "effectiveFrom", "effectiveTo"].includes(k)); if (unknown.length || !key) { res.status(400).json({ error: unknown.length ? "Unknown network fields." : "Idempotency-Key is required.", fieldErrors: unknown }); return; }
  const fromPortId = typeof b.fromPortId === "string" ? b.fromPortId : ""; const toPortId = typeof b.toPortId === "string" ? b.toPortId : null; const toInterfaceId = typeof b.toInterfaceId === "string" ? b.toInterfaceId : null; const branchId = typeof b.branchId === "string" ? b.branchId : ""; if (!fromPortId || !branchId || (Boolean(toPortId) === Boolean(toInterfaceId)) || !["physical", "logical", "wan"].includes(String(b.linkType))) { res.status(400).json({ error: "Exactly one target and valid linkType are required.", code: "VALIDATION_ERROR" }); return; }
  const user = await branchUser(req); if (!superUser(user) && user?.branchId !== branchId) { res.status(403).json({ error: "Branch is outside your scope." }); return; } const from = await prisma.networkPort.findUnique({ where: { id: fromPortId }, select: { asset: { select: { branchId: true } } } }); if (!from || (!superUser(user) && from.asset.branchId !== user?.branchId)) { res.status(403).json({ error: "Port is outside your scope." }); return; } if (toInterfaceId) { const target = await prisma.networkInterface.findUnique({ where: { id: toInterfaceId }, select: { asset: { select: { branchId: true } } } }); if (!target || (!superUser(user) && target.asset.branchId !== user?.branchId)) { res.status(403).json({ error: "Target interface is outside your scope." }); return; } }
  const hash = payloadHash(b); const prior = await prisma.portConnection.findUnique({ where: { idempotencyKey: key } }); if (prior) { if (prior.idempotencyPayloadHash !== hash) { res.status(409).json({ error: "Idempotency-Key was reused for different data.", code: "IDEMPOTENCY_KEY_REUSED" }); return; } res.json(prior); return; }
  const effectiveFrom = typeof b.effectiveFrom === "string" && !Number.isNaN(new Date(b.effectiveFrom).getTime()) ? new Date(b.effectiveFrom) : new Date(); const effectiveTo = typeof b.effectiveTo === "string" && !Number.isNaN(new Date(b.effectiveTo).getTime()) ? new Date(b.effectiveTo) : null; if (effectiveTo && effectiveTo <= effectiveFrom) { res.status(400).json({ error: "effectiveTo must be later than effectiveFrom.", code: "VALIDATION_ERROR" }); return; }
  const result = await prisma.$transaction(async (tx) => { await tx.portConnection.updateMany({ where: { fromPortId, effectiveTo: null }, data: { effectiveTo: effectiveFrom } }); const created = await tx.portConnection.create({ data: { fromPortId, toPortId, toInterfaceId, branchId, linkType: b.linkType as never, effectiveFrom, effectiveTo, idempotencyKey: key, idempotencyPayloadHash: hash } }); await tx.activityLog.create({ data: { userId: req.user!.id, action: "network_connection_created", entity: "PortConnection", entityId: created.id, metadata: { fromPortId, branchId, linkType: String(b.linkType) } } }); return created; }); broadcastChange({ entity: "PortConnection", action: "network_connection_created", entityId: result.id, branchId }); res.status(201).json(result);
});

const CREDENTIAL_FIELDS = ["username", "password", "snmpCommunity", "vpnKey", "wifiPassword", "apiKey", "recoveryCode"] as const;

router.post("/device-credentials", requireAuth, requirePermission("manage_infrastructure_assets"), async (req: AuthRequest, res) => {
  const b = req.body as Record<string, unknown>;
  const assetId = typeof b.assetId === "string" ? b.assetId : "";
  const unknownFields = Object.keys(b).filter((k) => k !== "assetId" && !(CREDENTIAL_FIELDS as readonly string[]).includes(k));
  if (unknownFields.length) { res.status(400).json({ error: "Unknown credential fields.", fieldErrors: unknownFields }); return; }
  if (!deviceCredentialKeyConfigured()) { res.status(503).json({ error: "Device credential encryption is not configured for this environment.", code: "CREDENTIAL_KEY_MISSING" }); return; }
  const asset = await prisma.asset.findUnique({ where: { id: assetId }, select: { branchId: true } });
  const user = await branchUser(req);
  if (!asset) { res.status(404).json({ error: "Asset not found." }); return; }
  if (!superUser(user) && user?.branchId !== asset.branchId) { res.status(403).json({ error: "Asset is outside your scope." }); return; }
  if (!(await featureEnabled(asset.branchId ?? undefined))) { res.status(503).json({ error: "Network infrastructure is disabled.", code: "NETWORK_DISABLED" }); return; }

  const payload: DeviceCredentialPayload = {};
  const flags: Record<string, boolean> = {};
  for (const field of CREDENTIAL_FIELDS) {
    const value = b[field];
    if (typeof value === "string" && value.trim()) { payload[field] = value.trim(); flags[`has${field[0].toUpperCase()}${field.slice(1)}`] = true; }
    else { flags[`has${field[0].toUpperCase()}${field.slice(1)}`] = false; }
  }
  const { ciphertext, iv, tag } = encryptDeviceCredentials(payload);

  const result = await prisma.$transaction(async (tx) => {
    const saved = await tx.networkDeviceCredential.upsert({
      where: { assetId },
      create: { assetId, ciphertext, iv, tag, updatedById: req.user!.id, ...flags },
      update: { ciphertext, iv, tag, updatedById: req.user!.id, ...flags },
    });
    await tx.activityLog.create({ data: { userId: req.user!.id, action: "network_device_credential_saved", entity: "NetworkDeviceCredential", entityId: saved.id, metadata: { assetId, fieldsSet: Object.keys(payload) } } });
    return saved;
  });
  res.json({ id: result.id, assetId: result.assetId, hasUsername: result.hasUsername, hasPassword: result.hasPassword, hasSnmpCommunity: result.hasSnmpCommunity, hasVpnKey: result.hasVpnKey, hasWifiPassword: result.hasWifiPassword, hasApiKey: result.hasApiKey, hasRecoveryCode: result.hasRecoveryCode, updatedAt: result.updatedAt });
});

export default router;
